import type { LanguageCatalogType, ResolvedLanguageSetsType } from "./types"

const EN: LanguageCatalogType = {
	stopwords: [
		"the",
		"a",
		"an",
		"please",
		"can",
		"could",
		"would",
		"you",
		"my",
		"me",
		"i",
		"to",
		"of",
		"is",
		"it",
		"do",
		"and",
		"for",
		"now",
		"all",
		"that",
		"this",
		"so",
		"but",
		"if",
		"or",
		"not",
		"yes",
		"thanks",
		"thank",
		"ok",
		"okay",
		"just",
		"some",
		"what",
		"how",
		"when",
		"where",
		"why",
		"who",
		"your",
		"we",
		"they",
		"as",
		"by",
		"from",
		"about",
		"right",
		"here",
		"there",
		"with",
		"was",
		"are",
		"be",
		"in",
		"on",
	],
	deviceGenericWords: [
		"light",
		"lights",
		"lamp",
		"lamps",
		"switch",
		"sensor",
		"cover",
		"the",
		"in",
		"on",
		"of",
	],
	numberWords: {
		one: 1,
		two: 2,
		three: 3,
		four: 4,
		five: 5,
		six: 6,
		seven: 7,
		eight: 8,
		nine: 9,
		ten: 10,
		fifteen: 15,
		twenty: 20,
		thirty: 30,
		sixty: 60,
	},
	timerKeywords: ["timer", "alarm"],
	memoryCommandKeywords: ["remember", "memorize", "forget", "don't forget"],
	unitWords: { hour: "hour", minute: "minute", second: "second", plural: "s" },
	affirmations: [
		"yes",
		"yeah",
		"yep",
		"yup",
		"sure",
		"ok",
		"okay",
		"do it",
		"go ahead",
		"confirm",
		"confirmed",
		"please do",
		"affirmative",
		"absolutely",
	],
	negations: [
		"no",
		"nope",
		"nah",
		"don't",
		"do not",
		"stop",
		"cancel",
		"never mind",
		"nevermind",
		"forget it",
		"negative",
	],
	phrases: {
		done: "Done.",
		gotIt: "Got it.",
		onIt: "On it.",
		thatIsDone: "That's done.",
		cantDoThat: "I couldn't do that.",
		cantAdjust: "I couldn't adjust that.",
		turnedOn: "Done, I turned on {name}.",
		turnedOff: "Done, I turned off {name}.",
		adjusted: "Got it, I adjusted {name}.",
		timerSet: "Timer set for {label}.",
		confirmAction: "Do you want me to go ahead with that?",
		cancelledAction: "Okay, I won't do that.",
		confirmReask: "Sorry, please answer yes or no.",
		fallbackLlm: "Sorry, I couldn't think of a reply. Please try again.",
		fallbackStt: "I didn't catch that. Could you say it again?",
		fallbackNetwork: "I had a network problem. One moment, please.",
		fallbackCapacity: "I'm helping another room right now. Give me a moment.",
		fallbackGeneric: "Sorry, something went wrong. Please try again.",
	},
}

const ES: LanguageCatalogType = {
	stopwords: [
		"el",
		"la",
		"los",
		"las",
		"un",
		"una",
		"unos",
		"unas",
		"de",
		"del",
		"al",
		"a",
		"en",
		"y",
		"o",
		"que",
		"por",
		"para",
		"con",
		"sin",
		"me",
		"te",
		"se",
		"lo",
		"le",
		"mi",
		"tu",
		"su",
		"es",
		"esta",
		"este",
		"eso",
		"esa",
		"ese",
		"si",
		"no",
		"ya",
		"ahora",
		"favor",
		"puedes",
		"puede",
		"quiero",
		"gracias",
		"como",
		"cuando",
		"donde",
		"cual",
		"quien",
		"aqui",
		"alli",
		"muy",
		"mas",
	],
	deviceGenericWords: [
		"luz",
		"luces",
		"lampara",
		"lamparas",
		"interruptor",
		"foco",
		"focos",
	],
	numberWords: {
		un: 1,
		una: 1,
		uno: 1,
		dos: 2,
		tres: 3,
		cuatro: 4,
		cinco: 5,
		seis: 6,
		siete: 7,
		ocho: 8,
		nueve: 9,
		diez: 10,
		quince: 15,
		veinte: 20,
		treinta: 30,
		sesenta: 60,
	},
	timerKeywords: ["temporizador", "alarma", "cronometro"],
	memoryCommandKeywords: [
		"recuerda",
		"recuérdalo",
		"recuerdalo",
		"acuérdate",
		"acuerdate",
		"memoriza",
		"olvida",
		"olvídate",
		"olvidate",
		"no olvides",
	],
	unitWords: { hour: "hora", minute: "minuto", second: "segundo", plural: "s" },
	affirmations: [
		"si",
		"sí",
		"claro",
		"vale",
		"dale",
		"hazlo",
		"adelante",
		"confirmo",
		"confirmado",
		"por favor",
		"correcto",
		"exacto",
	],
	negations: [
		"no",
		"nel",
		"cancela",
		"cancelar",
		"detente",
		"olvidalo",
		"olvídalo",
		"déjalo",
		"dejalo",
		"mejor no",
		"negativo",
	],
	phrases: {
		done: "Listo.",
		gotIt: "Hecho.",
		onIt: "Voy.",
		thatIsDone: "Ya está.",
		cantDoThat: "No pude hacerlo.",
		cantAdjust: "No pude ajustarlo.",
		turnedOn: "Listo, encendí {name}.",
		turnedOff: "Listo, apagué {name}.",
		adjusted: "Hecho, ajusté {name}.",
		timerSet: "Temporizador de {label}.",
		confirmAction: "¿Quieres que lo haga?",
		cancelledAction: "De acuerdo, no lo haré.",
		confirmReask: "Perdón, responde sí o no por favor.",
		fallbackLlm: "Perdón, no se me ocurrió una respuesta. Inténtalo de nuevo.",
		fallbackStt: "No te escuché bien. ¿Lo repites?",
		fallbackNetwork: "Tuve un problema de red. Un momento, por favor.",
		fallbackCapacity: "Estoy atendiendo otra habitación. Dame un momento.",
		fallbackGeneric: "Perdón, algo salió mal. Inténtalo de nuevo.",
	},
}

const CATALOGS: Record<string, LanguageCatalogType> = { en: EN, es: ES }

const resolvedCache = new Map<string, ResolvedLanguageSetsType>()

const normalizeLanguage = (language?: string | null): string => {
	const code = (language ?? "en").trim().toLowerCase().split(/[-_]/)[0]
	return CATALOGS[code] ? code : "en"
}

export const languageSetsFor = (
	language?: string | null,
): ResolvedLanguageSetsType => {
	const code = normalizeLanguage(language)
	const cached = resolvedCache.get(code)
	if (cached) return cached
	const extra = code === "en" ? null : CATALOGS[code]
	const resolved: ResolvedLanguageSetsType = {
		stopwords: new Set([...EN.stopwords, ...(extra?.stopwords ?? [])]),
		deviceGenericWords: new Set([
			...EN.deviceGenericWords,
			...(extra?.deviceGenericWords ?? []),
		]),
		numberWords: { ...EN.numberWords, ...(extra?.numberWords ?? {}) },
		timerKeywordsRe: new RegExp(
			`\\b(${[...EN.timerKeywords, ...(extra?.timerKeywords ?? [])].join("|")})\\b`,
			"i",
		),
		memoryCommandRe: new RegExp(
			`\\b(${[...EN.memoryCommandKeywords, ...(extra?.memoryCommandKeywords ?? [])].join("|")})\\b`,
			"i",
		),
		unitWords: extra?.unitWords ?? EN.unitWords,
		affirmations: new Set([...EN.affirmations, ...(extra?.affirmations ?? [])]),
		negations: new Set([...EN.negations, ...(extra?.negations ?? [])]),
		phrases: { ...EN.phrases, ...(extra?.phrases ?? {}) },
	}
	resolvedCache.set(code, resolved)
	return resolved
}
