export const RETRYABLE_GRPC_CODES = new Set([4, 14])

export const GRPC_CONNECTIVITY_STATE = {
	IDLE: 0,
	CONNECTING: 1,
	READY: 2,
	TRANSIENT_FAILURE: 3,
	SHUTDOWN: 4,
} as const

export const UNHEALTHY_GRPC_STATES: ReadonlySet<number> = new Set([
	GRPC_CONNECTIVITY_STATE.TRANSIENT_FAILURE,
	GRPC_CONNECTIVITY_STATE.SHUTDOWN,
])

export const GRPC_UNAVAILABLE_CODE = 14
export const GRPC_UNIMPLEMENTED_CODE = 12
export const GRPC_RESOURCE_EXHAUSTED_CODE = 8
