import type { ReloadSubsystemType, ReloaderScopeType } from "../types"

export const CONFIG_SECTION_META_FIELDS = [
	"id",
	"domiaId",
	"createdAt",
	"updatedAt",
	"isActive",
	"name",
] as const

export const DOMIA_LIVE_FIELDS = [
	"sessionIdTimeoutMs",
	"memoryWindowTurns",
	"memoryMaxAgeMs",
	"maxConcurrentVoiceReplies",
	"maxQueuedVoiceReplies",
	"voiceQueueTimeoutMs",
	"ownConfigTtlMs",
	"warmupOnBoot",
	"isHosted",
	"grpcUnaryDeadlineMs",
	"grpcStreamIdleTimeoutMs",
	"grpcStreamDeadlineMs",
	"peerStaleAfterMs",
	"modelInstallAllowedHosts",
	"heartbeatSignatureRequired",
	"knowledgeMaxChars",
	"meshSecretGraceMs",
	"benchTurns",
	"benchThresholds",
] as const

export const DOMIA_UNTRACKED_FIELDS = [
	"id",
	"name",
	"domiaKey",
	"isActive",
	"localIp",
	"grpcPort",
	"grpcTls",
	"lastSeenAt",
	"peerNodeId",
	"configRevision",
	"configReloadDrainMs",
	"createdAt",
	"updatedAt",
] as const

export const MODULES_SKILLS_FIELDS = ["skillsEngine"] as const

export const MODULES_PROACTIVITY_FIELDS = ["proactivityEngine"] as const

export const MODULES_LIVE_FIELDS = [
	"emotionEngine",
	"emotionCapture",
	"memoryEngine",
	"factCapture",
	"factRecall",
	"environmentTimeEnabled",
	"reflectionOnlyWhenIdle",
	"reflectionConcurrency",
	"reflectionQueueMaxDepth",
	"reflectionYieldToVoice",
	"reflectionTimeoutMs",
	"reflectionIdlePollMs",
	"reflectionIdleGraceMs",
	"reflectionMaxIdleWaitMs",
	"reflectionSlotTimeoutMs",
	"reflectionYieldMaxAttempts",
	"identityEngine",
	"metricsSampleResources",
	"turnEventsPersist",
	"proactiveIdleNudgeEnabled",
	"proactiveIdleNudgeAfterMs",
	"proactiveIdleNudgeMinIntervalMs",
	"proactiveQuietHoursStart",
	"proactiveQuietHoursEnd",
	"proactiveMaxPerHour",
	"proactiveMaxPerDay",
	"proactiveChimeEnabled",
	"proactiveDeferMaxMs",
	"proactiveTickMs",
	"proactiveLeaseMs",
	"proactiveMaxAttempts",
	"proactiveRetryBackoffMs",
] as const

export const STT_LIVE_FIELDS = [
	"language",
	"silenceThreshold",
	"bufferSize",
	"timeoutMs",
	"enableEndpoint",
	"decodePaddingMs",
	"rule1MinTrailingSilence",
	"rule2MinTrailingSilence",
	"rule3MinUtteranceLength",
] as const

export const STT_POOL_FIELDS = [
	"engine",
	"modelName",
	"baseUrl",
	"apiKey",
	"modelPath",
	"quantization",
	"numThreads",
	"provider",
	"partialAtEndpointEnabled",
	"poolWarmWorkers",
	"poolMaxWorkers",
	"poolAutoScaleEnabled",
	"poolIdleTimeoutMs",
	"poolQueueMaxDepth",
	"poolQueueTimeoutMs",
	"poolExecutionTimeoutMs",
	"maxConcurrentStreamingSessions",
	"sessionIdleTimeoutMs",
	"workerRecycleAfterJobs",
] as const

export const TTS_LIVE_FIELDS = [
	"sentenceFirstFragmentMaxWords",
	"phraseCacheMaxBytes",
	"phraseCacheWarmupEnabled",
	"phraseCacheReplyUnitsEnabled",
	"voiceName",
	"language",
	"pitch",
	"speed",
	"silenceScale",
	"streamingEnabled",
	"sentenceSoftFlushMinChars",
	"sentenceFirstUnitMaxWords",
	"sentenceMediumFlushChars",
	"sentenceHardFlushChars",
	"sentenceFirstFlushMaxMs",
	"pipelineMaxQueueDepth",
	"pipelineEagerTtsSentences",
] as const

export const TTS_POOL_FIELDS = [
	"engine",
	"modelPath",
	"espeakNgDataPath",
	"engineConfig",
	"quantization",
	"numThreads",
	"provider",
	"maxNumSentences",
	"pacerEnabled",
	"pacerMinRemainingMs",
	"pacerMaxChars",
	"poolWarmWorkers",
	"poolMaxWorkers",
	"poolAutoScaleEnabled",
	"poolIdleTimeoutMs",
	"poolQueueMaxDepth",
	"poolQueueTimeoutMs",
	"poolExecutionTimeoutMs",
	"phraseCacheEnabled",
	"phraseCacheEntries",
	"phraseCacheMaxChars",
	"workerRecycleAfterJobs",
] as const

export const LLM_DRAIN_FIELDS = ["engine", "baseUrl", "apiKey"] as const

export const LLM_LIVE_FIELDS = [
	"modelName",
	"reflectionModelName",
	"temperature",
	"contextWindow",
	"numPredict",
	"llmConcurrency",
	"keepAliveMs",
	"streamUsage",
	"useCompactPrompt",
	"agentPromptMode",
	"skillsRouting",
	"intentModelName",
	"embeddingModelName",
	"intentEmbedThreshold",
	"descriptorRoutingEnabled",
	"toolModelName",
	"agentMaxSteps",
	"agentBudgetMs",
	"confirmationTtlMs",
	"agentAckAfterMs",
	"toolShortlistMax",
	"matcherEngine",
	"matcherSemanticThreshold",
	"matcherRrfK",
	"matcherCascadeExit",
	"embedBackend",
	"embedModelPath",
	"slotAffinityEnabled",
	"repeatPenalty",
	"topK",
	"minP",
	"seed",
	"stopSequences",
	"toolTemperature",
	"toolNumPredict",
	"asyncFollowUpPolicy",
	"asyncFollowUpMaxWaitMs",
	"llmStreamIdleMs",
	"quietAudioPollMs",
	"quietAudioDeadlineMs",
	"agentRepeatWarnAt",
	"agentRepeatBlockAt",
	"agentMaxToolCallsPerTurn",
	"agentRecentToolsTurns",
	"anaphoraMaxAgeMs",
	"fastPathEnabled",
	"fastPathMinCoverage",
	"fastPathMaxUtteranceChars",
	"fastPathBlocklistEnabled",
	"constrainedRepairEnabled",
	"slotWaitTimeoutMs",
	"slotWaitPollMs",
	"intentLlmOnSingleSlot",
	"agentDecisionMode",
	"authoredSpeechEnabled",
	"agentQuestionGuardEnabled",
	"agentTargetGuardEnabled",
	"agentReadThenAnswerEnabled",
	"toolRequestMaxRetries",
	"fastPathCompoundEnabled",
	"fastPathCompoundMaxTargets",
] as const

export const WAKE_WORD_LISTENER_FIELDS = [
	"engine",
	"wakeWord",
	"sensitivity",
	"threshold",
	"cooldown",
	"numThreads",
	"provider",
	"framework",
	"model",
	"customModelPath",
	"quantization",
	"vadEngine",
	"vadModelPath",
	"inputDeviceIndex",
	"sampleRate",
	"bitsPerSample",
	"channels",
	"aecEnabled",
	"aecBackend",
	"aecMethod",
	"aecSourceMaster",
	"aecSinkMaster",
	"aecSourceName",
	"aecSinkName",
	"aecSetDefaultDevices",
	"denoiseEnabled",
	"denoiseEngine",
	"denoiseModelPath",
	"denoiseNumThreads",
	"denoiseProvider",
	"echoResidualGateEnabled",
	"echoResidualMinRatio",
	"echoResidualWindowMs",
	"echoResidualMaxDelayMs",
	"echoResidualMinRms",
	"echoResidualMinFrames",
	"wakeVerifier",
	"wakeVerifierWindowMs",
	"wakeVerifierMinRms",
	"wakeVerifierMinSpeechMs",
	"wakeVerifierMinScore",
] as const

export const WAKE_WORD_LIVE_FIELDS = [
	"vadThreshold",
	"vadMinSilenceS",
	"vadEndOfSpeechMs",
	"maxRecordingMs",
	"followUpWindowMs",
	"bargeInEnabled",
	"speculativeSilenceMs",
	"satelliteSpeculationEnabled",
	"semanticEndpointingEnabled",
	"acousticEndpointingEnabled",
	"acousticEndpointCompleteThreshold",
	"acousticGateCooldownMs",
	"acousticMaxHoldMs",
	"acousticTailKeepMs",
	"acousticLocalMaxHoldMs",
	"bargeInMinRms",
	"suppressWakeWhilePeerSpeaks",
	"turnDetectorEngine",
	"turnDetectorModelPath",
	"speculativeTtsEnabled",
	"speculateWithSkills",
	"speculationSkillGateMaxScore",
	"twoTierEndpointEnabled",
	"twoTierEagerMinPartialChars",
	"twoTierPrefillIdleGuardMs",
	"twoTierResumeGraceMs",
	"twoTierMaxEagerPrefills",
	"sharedMicStreamEnabled",
	"endpointCompleteMs",
	"endpointIncompleteMs",
	"endpointWaitMs",
	"dynamicEndpointingEnabled",
	"dynamicEndpointMinMs",
	"dynamicEndpointMaxMs",
	"dynamicEndpointAlpha",
	"dynamicEndpointMargin",
	"pauseBargeInEnabled",
	"falseInterruptionTimeoutMs",
	"echoSuppressEnabled",
	"echoSuppressMarginMs",
	"followUpLeadPadMs",
	"stopWordAbortEnabled",
	"stopWordMaxWords",
] as const

export const CONFIG_SECTION_PROPS: { section: string; prop: string }[] = [
	{ section: "character", prop: "characterProfile" },
	{ section: "emotion", prop: "emotionState" },
	{ section: "modules", prop: "moduleSettings" },
	{ section: "capabilities", prop: "runtimeCapabilities" },
	{ section: "stt", prop: "sttConfig" },
	{ section: "tts", prop: "ttsConfig" },
	{ section: "llm", prop: "llmModelConfig" },
	{ section: "wakeWord", prop: "wakeWordConfig" },
	{ section: "playback", prop: "audioPlaybackConfig" },
	{ section: "mqttLocal", prop: "localMqttConfig" },
]

export const RELOAD_SCOPE: Record<ReloadSubsystemType, ReloaderScopeType> = {
	"stt-pool": "global",
	"tts-pool": "global",
	mqtt: "global",
	"voice-listener": "per-identity",
	skills: "per-identity",
	satellites: "per-identity",
	identity: "per-identity",
	proactivity: "per-identity",
}
