export const DEFAULT_SATELLITE_SAMPLE_RATE = 16000
export const DEFAULT_SATELLITE_CHANNELS = 1
export const MAX_UTTERANCE_BYTES = 5_000_000
export const NO_VAD_MAX_UTTERANCE_S = 12
export const PRE_SPEECH_ROLL_BYTES = 64_000
