export const AUTO_MAX_WORKERS_FLOOR = 2
export const AUTO_MAX_WORKERS_CEILING = 4
export const AUTO_CORE_DIVISOR = 3
export const AUTO_GB_PER_WORKER = 1.5

export const RESPAWN_BACKOFF_BASE_MS = 500
export const RESPAWN_BACKOFF_MAX_MS = 30000
export const RESPAWN_MAX_ATTEMPTS = 5
