export const REFLECTION_TIMEOUT_MS = 15_000
export const REFLECTION_IDLE_POLL_MS = 250
export const REFLECTION_MAX_IDLE_WAIT_MS = 20_000
export const REFLECTION_SLOT_TIMEOUT_MS = 30_000
export const REFLECTION_YIELD_MAX_ATTEMPTS = 3
