export const DEFAULT_TIMEOUT_MS = 15_000
export const DEFAULT_RETRY_DELAY_MS = 250
export const MAX_RETRY_AFTER_MS = 30_000
export const DEFAULT_RETRYABLE_PATTERN =
	/ECONNREFUSED|ECONNRESET|ETIMEDOUT|fetch failed|HTTP (429|50[234])/i
