export const DEFAULT_LANGUAGE = "en"
export const DEFAULT_IS_HOSTED = false
export const DEFAULT_ENVIRONMENT_TIME_ENABLED = true
export const DEFAULT_MAX_CONCURRENT_VOICE_REPLIES = 1
export const DEFAULT_MAX_QUEUED_VOICE_REPLIES = 4
export const DEFAULT_VOICE_QUEUE_TIMEOUT_MS = 15_000
export const DEFAULT_OWN_CONFIG_TTL_MS = 30_000
export const DEFAULT_WARMUP_ON_BOOT = true
export const PERSONALITY_ENUM = {
	OPTIMISTIC: "OPTIMISTIC",
	CALM: "CALM",
	ANALYTICAL: "ANALYTICAL",
	EMPATHETIC: "EMPATHETIC",
	NEUTRAL: "NEUTRAL",
	PLAYFUL: "PLAYFUL",
	CAUTIOUS: "CAUTIOUS",
	ADAPTIVE: "ADAPTIVE",
	CUSTOM: "CUSTOM",
} as const
export const PERSONALITY_ENUM_VALUES = [
	PERSONALITY_ENUM.OPTIMISTIC,
	PERSONALITY_ENUM.CALM,
	PERSONALITY_ENUM.ANALYTICAL,
	PERSONALITY_ENUM.EMPATHETIC,
	PERSONALITY_ENUM.NEUTRAL,
	PERSONALITY_ENUM.PLAYFUL,
	PERSONALITY_ENUM.CAUTIOUS,
	PERSONALITY_ENUM.ADAPTIVE,
	PERSONALITY_ENUM.CUSTOM,
] as const
export const PROFESSION_ENUM = {
	HOST: "HOST",
	CHEF: "CHEF",
	BARTENDER: "BARTENDER",
	TECHNICIAN: "TECHNICIAN",
	GUARDIAN: "GUARDIAN",
	ARTIST: "ARTIST",
	STORYTELLER: "STORYTELLER",
	PSYCHOLOGIST: "PSYCHOLOGIST",
	NONE: "NONE",
} as const
export const PROFESSION_ENUM_VALUES = [
	PROFESSION_ENUM.HOST,
	PROFESSION_ENUM.CHEF,
	PROFESSION_ENUM.BARTENDER,
	PROFESSION_ENUM.TECHNICIAN,
	PROFESSION_ENUM.GUARDIAN,
	PROFESSION_ENUM.ARTIST,
	PROFESSION_ENUM.STORYTELLER,
	PROFESSION_ENUM.PSYCHOLOGIST,
	PROFESSION_ENUM.NONE,
] as const
export const COMMUNICATION_STYLE_ENUM = {
	FRIENDLY: "FRIENDLY",
	FORMAL: "FORMAL",
	CASUAL: "CASUAL",
	SARCASTIC: "SARCASTIC",
	RESERVED: "RESERVED",
	ENTHUSIASTIC: "ENTHUSIASTIC",
	NEUTRAL: "NEUTRAL",
} as const
export const COMMUNICATION_STYLE_ENUM_VALUES = [
	COMMUNICATION_STYLE_ENUM.FRIENDLY,
	COMMUNICATION_STYLE_ENUM.FORMAL,
	COMMUNICATION_STYLE_ENUM.CASUAL,
	COMMUNICATION_STYLE_ENUM.SARCASTIC,
	COMMUNICATION_STYLE_ENUM.RESERVED,
	COMMUNICATION_STYLE_ENUM.ENTHUSIASTIC,
	COMMUNICATION_STYLE_ENUM.NEUTRAL,
] as const
export const PERCEIVED_AGE_ENUM = {
	CHILD: "CHILD",
	TEEN: "TEEN",
	YOUNG_ADULT: "YOUNG_ADULT",
	ADULT: "ADULT",
	SENIOR: "SENIOR",
} as const
export const PERCEIVED_AGE_ENUM_VALUES = [
	PERCEIVED_AGE_ENUM.CHILD,
	PERCEIVED_AGE_ENUM.TEEN,
	PERCEIVED_AGE_ENUM.YOUNG_ADULT,
	PERCEIVED_AGE_ENUM.ADULT,
	PERCEIVED_AGE_ENUM.SENIOR,
] as const
export const KNOWLEDGE_DEPTH_ENUM = {
	BASIC: "BASIC",
	INTERMEDIATE: "INTERMEDIATE",
	ADVANCED: "ADVANCED",
	EXPERT: "EXPERT",
} as const
export const KNOWLEDGE_DEPTH_ENUM_VALUES = [
	KNOWLEDGE_DEPTH_ENUM.BASIC,
	KNOWLEDGE_DEPTH_ENUM.INTERMEDIATE,
	KNOWLEDGE_DEPTH_ENUM.ADVANCED,
	KNOWLEDGE_DEPTH_ENUM.EXPERT,
] as const
export const RELATIONSHIP_TYPE_ENUM = {
	COMPANION: "COMPANION",
	GUIDE: "GUIDE",
	TEACHER: "TEACHER",
	HELPER: "HELPER",
	GUARDIAN: "GUARDIAN",
	ENTERTAINER: "ENTERTAINER",
} as const
export const RELATIONSHIP_TYPE_ENUM_VALUES = [
	RELATIONSHIP_TYPE_ENUM.COMPANION,
	RELATIONSHIP_TYPE_ENUM.GUIDE,
	RELATIONSHIP_TYPE_ENUM.TEACHER,
	RELATIONSHIP_TYPE_ENUM.HELPER,
	RELATIONSHIP_TYPE_ENUM.GUARDIAN,
	RELATIONSHIP_TYPE_ENUM.ENTERTAINER,
] as const
export const ROLE_MODE_ENUM = {
	ACTIVE: "ACTIVE",
	PASSIVE: "PASSIVE",
	OBSERVER: "OBSERVER",
	ADVISOR: "ADVISOR",
} as const
export const ROLE_MODE_ENUM_VALUES = [
	ROLE_MODE_ENUM.ACTIVE,
	ROLE_MODE_ENUM.PASSIVE,
	ROLE_MODE_ENUM.OBSERVER,
	ROLE_MODE_ENUM.ADVISOR,
] as const
export const CAPABILITY_ENUM = {
	RECORD: "record",
	STT: "stt",
	LLM: "llm",
	TTS: "tts",
	PLAYBACK: "playback",
} as const
export const CAPABILITY_ENUM_VALUES = [
	CAPABILITY_ENUM.RECORD,
	CAPABILITY_ENUM.STT,
	CAPABILITY_ENUM.LLM,
	CAPABILITY_ENUM.TTS,
	CAPABILITY_ENUM.PLAYBACK,
] as const
