export const DEFAULT_MEMORY_WINDOW_TURNS = 8
export const DEFAULT_MEMORY_MAX_AGE_MS = 1_800_000
export const DEFAULT_REFLECTION_ONLY_WHEN_IDLE = true
export const DEFAULT_REFLECTION_CONCURRENCY = 2
export const DEFAULT_REFLECTION_QUEUE_MAX_DEPTH = 12
export const DEFAULT_REFLECTION_YIELD_TO_VOICE = true
export const DEFAULT_REFLECTION_TIMEOUT_MS = 15_000
export const DEFAULT_REFLECTION_IDLE_POLL_MS = 250
export const DEFAULT_REFLECTION_IDLE_GRACE_MS = 15_000
export const DEFAULT_REFLECTION_MAX_IDLE_WAIT_MS = 180_000
export const DEFAULT_REFLECTION_SLOT_TIMEOUT_MS = 30_000
export const DEFAULT_REFLECTION_YIELD_MAX_ATTEMPTS = 3
export const DEFAULT_KNOWLEDGE_MAX_CHARS = 20_000
export const FACT_KIND_ENUM = {
	USER_FACT: "user_fact",
	PREFERENCE: "preference",
	OBSERVATION: "observation",
} as const
export const FACT_KIND_ENUM_VALUES = [
	FACT_KIND_ENUM.USER_FACT,
	FACT_KIND_ENUM.PREFERENCE,
	FACT_KIND_ENUM.OBSERVATION,
] as const
export const DEFAULT_FACT_KIND = FACT_KIND_ENUM.OBSERVATION
export const FACT_SOURCE_KIND_ENUM = {
	STATED: "stated",
	INFERRED: "inferred",
	IMPORTED: "imported",
} as const
export const FACT_SOURCE_KIND_ENUM_VALUES = [
	FACT_SOURCE_KIND_ENUM.STATED,
	FACT_SOURCE_KIND_ENUM.INFERRED,
	FACT_SOURCE_KIND_ENUM.IMPORTED,
] as const
export const DEFAULT_FACT_SOURCE_KIND = FACT_SOURCE_KIND_ENUM.STATED
export const DEFAULT_MEMORY_RECALL_INCLUDE_EXPIRED = false
export const DEFAULT_MEMORY_FACT_MAX_AGE_DAYS: number | null = null
export const EMOTION_EXPRESSION_STYLE_ENUM = {
	MINIMAL: "minimal",
	BALANCED: "balanced",
	TALKATIVE: "talkative",
} as const
export const EMOTION_EXPRESSION_STYLE_ENUM_VALUES = [
	EMOTION_EXPRESSION_STYLE_ENUM.MINIMAL,
	EMOTION_EXPRESSION_STYLE_ENUM.BALANCED,
	EMOTION_EXPRESSION_STYLE_ENUM.TALKATIVE,
] as const
export const DEFAULT_EMOTION_EXPRESSION_STYLE =
	EMOTION_EXPRESSION_STYLE_ENUM.BALANCED
export const DEFAULT_EMOTION_EVENT_MAX_AGE_MS = 90 * 86_400_000
export const DEFAULT_EMOTION_EVENT_MAX_ROWS_PER_DOMIA = 5_000
export const DEFAULT_MEMORY_FACT_MAX_ROWS_PER_DOMIA = 2_000
export const DEFAULT_MEMORY_EPISODE_MAX_AGE_MS = 180 * 86_400_000
export const DEFAULT_MEMORY_EPISODE_MAX_ROWS_PER_DOMIA = 1_000
