export const DEFAULT_LLM_CONCURRENCY = 3
export const DEFAULT_WAKE_WORD = "computer"
export const DEFAULT_WAKE_WORD_MODEL = "kws-zipformer-gigaspeech"
export const DEFAULT_WAKE_WORD_MODEL_PATH =
	"data/models/kws-zipformer-gigaspeech-3.3M-2024-01-01"
export const VAD_ENGINE_ENUM = {
	SILERO: "SILERO",
} as const
export const VAD_ENGINE_ENUM_VALUES = [VAD_ENGINE_ENUM.SILERO] as const
export const DEFAULT_VAD_ENGINE = VAD_ENGINE_ENUM.SILERO
export const DEFAULT_VAD_MODEL_PATH = "data/models/silero_vad.onnx"
export const DEFAULT_WAKE_WORD_SENSITIVITY = 1.0
export const DEFAULT_WAKE_WORD_THRESHOLD = 0.25
export const DEFAULT_WAKE_WORD_COOLDOWN_S = 2.0
export const DEFAULT_WAKE_WORD_NUM_THREADS = 1
export const DEFAULT_WAKE_WORD_PROVIDER = "cpu"
export const DEFAULT_VAD_THRESHOLD = 0.5
export const DEFAULT_VAD_MIN_SILENCE_S = 0.5
export const DEFAULT_VAD_PREWARM_ON_BOOT = true
export const DEFAULT_VAD_END_OF_SPEECH_MS = 200
export const DEFAULT_FOLLOW_UP_WINDOW_MS = 8000
export const DEFAULT_BARGE_IN_ENABLED = true
export const DEFAULT_SPECULATIVE_SILENCE_MS = 300
export const DEFAULT_SEMANTIC_ENDPOINTING_ENABLED = false
export const DEFAULT_ACOUSTIC_ENDPOINTING_ENABLED = false
export const DEFAULT_SUPPRESS_WAKE_WHILE_PEER_SPEAKS = true
export const DEFAULT_ACOUSTIC_ENDPOINT_THRESHOLD = 0.85
export const DEFAULT_ACOUSTIC_GATE_COOLDOWN_MS = 250
export const DEFAULT_ACOUSTIC_MAX_HOLD_MS = 2000
export const DEFAULT_ACOUSTIC_TAIL_KEEP_MS = 150
export const DEFAULT_ACOUSTIC_LOCAL_MAX_HOLD_MS = 1000
export const DEFAULT_BARGE_IN_MIN_RMS = 0.008
export const TURN_DETECTOR_ENGINE_ENUM = {
	SMART_TURN: "SMART_TURN",
} as const
export const TURN_DETECTOR_ENGINE_ENUM_VALUES = [
	TURN_DETECTOR_ENGINE_ENUM.SMART_TURN,
] as const
export const DEFAULT_TURN_DETECTOR_ENGINE = TURN_DETECTOR_ENGINE_ENUM.SMART_TURN
export const DEFAULT_TURN_DETECTOR_MODEL_PATH =
	"data/models/smart-turn/smart-turn-v3.2-cpu.onnx"
export const DEFAULT_SPECULATIVE_TTS_ENABLED = false
export const DEFAULT_SPECULATE_WITH_SKILLS = false
export const DEFAULT_SPECULATION_SKILL_GATE_MAX_SCORE = 0
export const DEFAULT_TWO_TIER_ENDPOINT_ENABLED = false
export const DEFAULT_TWO_TIER_EAGER_MIN_PARTIAL_CHARS = 8
export const DEFAULT_TWO_TIER_PREFILL_IDLE_GUARD_MS = 150
export const DEFAULT_TWO_TIER_RESUME_GRACE_MS = 300
export const DEFAULT_TWO_TIER_MAX_EAGER_PREFILLS = 3
export const DEFAULT_TWO_TIER_SETTLE_MAX_WAIT_MS = 1500
export const DEFAULT_SPECULATION_MAX_ATTEMPTS = 3
export const DEFAULT_SPECULATION_MAX_UTTERANCE_MS = 10_000
export const DEFAULT_SHARED_MIC_STREAM_ENABLED = false
export const DEFAULT_ENDPOINT_COMPLETE_MS = 350
export const DEFAULT_DYNAMIC_ENDPOINTING_ENABLED = false
export const DEFAULT_DYNAMIC_ENDPOINT_MIN_MS = 300
export const DEFAULT_DYNAMIC_ENDPOINT_MAX_MS = 1500
export const DEFAULT_DYNAMIC_ENDPOINT_ALPHA = 0.9
export const DEFAULT_DYNAMIC_ENDPOINT_MARGIN = 1.5
export const DEFAULT_PAUSE_BARGE_IN_ENABLED = false
export const DEFAULT_FALSE_INTERRUPTION_TIMEOUT_MS = 2000
export const DEFAULT_TTS_PACER_ENABLED = false
export const DEFAULT_TTS_PACER_MIN_REMAINING_MS = 5000
export const DEFAULT_TTS_PACER_MAX_CHARS = 300
export const DEFAULT_ECHO_SUPPRESS_ENABLED = false
export const DEFAULT_ECHO_SUPPRESS_MARGIN_MS = 500
export const DEFAULT_ENDPOINT_INCOMPLETE_MS = 900
export const DEFAULT_ENDPOINT_WAIT_MS = 1400
export const DEFAULT_FOLLOW_UP_LEAD_PAD_MS = 300
export const AEC_BACKEND_ENUM = {
	AUTO: "AUTO",
	PIPEWIRE: "PIPEWIRE",
	PULSEAUDIO: "PULSEAUDIO",
} as const
export const AEC_BACKEND_ENUM_VALUES = [
	AEC_BACKEND_ENUM.AUTO,
	AEC_BACKEND_ENUM.PIPEWIRE,
	AEC_BACKEND_ENUM.PULSEAUDIO,
] as const
export const DEFAULT_AEC_ENABLED = false
export const DEFAULT_AEC_BACKEND = AEC_BACKEND_ENUM.AUTO
export const DEFAULT_AEC_METHOD = "webrtc"
export const DEFAULT_AEC_SOURCE_NAME = "domia_aec_source"
export const DEFAULT_AEC_SINK_NAME = "domia_aec_sink"
export const DEFAULT_AEC_SET_DEFAULT_DEVICES = true
export const SPEECH_ENHANCER_ENGINE_ENUM = {
	GTCRN: "GTCRN",
	DPDFNET: "DPDFNET",
} as const
export const SPEECH_ENHANCER_ENGINE_ENUM_VALUES = [
	SPEECH_ENHANCER_ENGINE_ENUM.GTCRN,
	SPEECH_ENHANCER_ENGINE_ENUM.DPDFNET,
] as const
export const DEFAULT_DENOISE_ENABLED = false
export const DEFAULT_DENOISE_ENGINE = SPEECH_ENHANCER_ENGINE_ENUM.DPDFNET
export const DEFAULT_GTCRN_MODEL_PATH = "data/models/gtcrn_simple.onnx"
export const DEFAULT_DENOISE_MODEL_PATH = "data/models/dpdfnet_baseline.onnx"
export const DEFAULT_DENOISE_NUM_THREADS = 1
export const DEFAULT_DENOISE_PROVIDER = "cpu"
export const DEFAULT_ECHO_RESIDUAL_GATE_ENABLED = false
export const DEFAULT_ECHO_RESIDUAL_MIN_RATIO = 0.62
export const DEFAULT_ECHO_RESIDUAL_WINDOW_MS = 100
export const DEFAULT_ECHO_RESIDUAL_MAX_DELAY_MS = 1500
export const DEFAULT_ECHO_RESIDUAL_MIN_RMS = 0.018
export const DEFAULT_ECHO_RESIDUAL_MIN_FRAMES = 3
export const DEFAULT_ECHO_REFERENCE_SECONDS = 4
export const DEFAULT_ECHO_LIVE_SPEECH_TTL_MS = 1500
export const DEFAULT_STOP_WORD_ABORT_ENABLED = false
export const DEFAULT_STOP_WORD_MAX_WORDS = 4
export const DEFAULT_STOP_WORD_MAX_EXTRA_WORDS = 1
export const WAKE_VERIFIER_ENUM = {
	NONE: "NONE",
	ENERGY: "ENERGY",
	STT: "STT",
} as const
export const WAKE_VERIFIER_ENUM_VALUES = [
	WAKE_VERIFIER_ENUM.NONE,
	WAKE_VERIFIER_ENUM.ENERGY,
	WAKE_VERIFIER_ENUM.STT,
] as const
export const DEFAULT_WAKE_VERIFIER = WAKE_VERIFIER_ENUM.NONE
export const DEFAULT_WAKE_VERIFIER_WINDOW_MS = 1500
export const DEFAULT_WAKE_VERIFIER_MIN_RMS = 0.01
export const DEFAULT_WAKE_VERIFIER_MIN_SPEECH_MS = 200
export const DEFAULT_WAKE_VERIFIER_MIN_SCORE = 0.6
export const DEFAULT_WAKE_VERIFIER_MAX_MS = 400
export const DEFAULT_SENTENCE_SOFT_FLUSH_MIN_CHARS = 20
export const DEFAULT_SENTENCE_FIRST_UNIT_MAX_WORDS = 5
export const DEFAULT_SENTENCE_MEDIUM_FLUSH_CHARS = 60
export const DEFAULT_SENTENCE_HARD_FLUSH_CHARS = 200
export const DEFAULT_SENTENCE_FIRST_FLUSH_MAX_MS = 800
export const DEFAULT_PIPELINE_MAX_QUEUE_DEPTH = 4
export const DEFAULT_PIPELINE_EAGER_TTS_SENTENCES = 2
export const DEFAULT_PCM_SAMPLE_RATE = 16000
export const DEFAULT_AUDIO_CAPTURE_SAMPLE_RATE = DEFAULT_PCM_SAMPLE_RATE
export const DEFAULT_AUDIO_CAPTURE_BITS_PER_SAMPLE = 16
export const DEFAULT_AUDIO_CAPTURE_CHANNELS = 1
export const DEFAULT_AUDIO_CAPTURE_MAX_RECORDING_MS = 15000
export const DEFAULT_LLM_MODEL_TEMPERATURE = 0.7
export const DEFAULT_LLM_MODEL_CONTEXT_WINDOW = 4096
export const DEFAULT_LLM_MODEL_NUM_PREDICT = 80
export const DEFAULT_STT_MODEL_NAME = "parakeet-tdt-06b-v2"
export const DEFAULT_STT_TIMEOUT_MS = 5000
export const DEFAULT_STT_MODEL_PATH = "data/models/parakeet-tdt-06b-v2"
export const NEMOTRON_STREAMING_AUTO_LANGUAGE = "auto"
export const DEFAULT_STT_ENABLE_ENDPOINT = true
export const DEFAULT_STT_RULE1_MIN_TRAILING_SILENCE = 1.2
export const DEFAULT_STT_RULE2_MIN_TRAILING_SILENCE = 0.6
export const DEFAULT_STT_RULE3_MIN_UTTERANCE_LENGTH = 12
export const DEFAULT_STT_NUM_THREADS = 2
export const DEFAULT_STT_PROVIDER = "cpu"
export const DEFAULT_STT_DECODE_PADDING_MS = 600
export const DEFAULT_STT_FLUSH_PADDING_MS = 600
export const DEFAULT_STT_PARTIAL_AT_ENDPOINT_ENABLED = false
export const DEFAULT_STT_POOL_WARM_WORKERS = 1
export const DEFAULT_STT_POOL_MAX_WORKERS = 0
export const DEFAULT_STT_POOL_AUTO_SCALE_ENABLED = true
export const DEFAULT_STT_POOL_IDLE_TIMEOUT_MS = 60_000
export const DEFAULT_STT_POOL_QUEUE_MAX_DEPTH = 8
export const DEFAULT_STT_POOL_QUEUE_TIMEOUT_MS = 15_000
export const DEFAULT_STT_POOL_EXECUTION_TIMEOUT_MS = 30_000
export const DEFAULT_STT_MAX_CONCURRENT_STREAMING_SESSIONS = 0
export const DEFAULT_STT_SESSION_IDLE_TIMEOUT_MS = 10_000
export const DEFAULT_STT_WORKER_RECYCLE_AFTER_JOBS = 0
export const DEFAULT_LLM_MODEL_NAME = "llama3.2:3b"
export const DEFAULT_OLLAMA_HOST = "http://localhost:11434"
export const DEFAULT_OLLAMA_KEEP_ALIVE_MS = -1
export const DEFAULT_TTS_VOICE_NAME = "af_heart"
export const DEFAULT_TTS_MODEL_PATH = "data/models/kokoro-multi-lang-v1_0"
export const DEFAULT_POCKET_MODEL_PATH =
	"data/models/sherpa-onnx-pocket-tts-int8-2026-01-26"
export const DEFAULT_POCKET_NUM_STEPS = 5
export const DEFAULT_POCKET_REFERENCE_WAV = "test_wavs/bria.wav"
export const DEFAULT_POCKET_VOICE_CACHE = 50
export const DEFAULT_SUPERTONIC_MODEL_PATH =
	"data/models/sherpa-onnx-supertonic-3-tts-int8-2026-05-11"
export const DEFAULT_SUPERTONIC_NUM_STEPS = 5
export const DEFAULT_SENTENCE_FIRST_FRAGMENT_MAX_WORDS = 0
export const DEFAULT_TTS_PHRASE_CACHE_MAX_BYTES = 8_000_000
export const DEFAULT_TTS_PHRASE_CACHE_WARMUP_ENABLED = false
export const DEFAULT_TTS_PHRASE_CACHE_REPLY_UNITS_ENABLED = false
export const DEFAULT_TTS_PHRASE_CACHE_VOICE_STEP = 0.05
export const DEFAULT_TTS_PREWARM_ON_BOOT = true
export const DEFAULT_TTS_PREWARM_ON_RELOAD = true
export const DEFAULT_TTS_PREWARM_PASSES = 2
export const DEFAULT_MATCHA_VOCODER_PATH = "data/models/vocos-22khz-univ.onnx"
export const DEFAULT_TTS_NUM_THREADS = 2
export const DEFAULT_TTS_PROVIDER = "cpu"
export const DEFAULT_TTS_MAX_NUM_SENTENCES = 1
export const DEFAULT_TTS_SILENCE_SCALE = 0.2
export const DEFAULT_TTS_SPEED = 1.0
export const DEFAULT_TTS_STREAMING_ENABLED = true
export const DEFAULT_TTS_PHRASE_CACHE_ENABLED = true
export const DEFAULT_TTS_PHRASE_CACHE_ENTRIES = 32
export const DEFAULT_TTS_PHRASE_CACHE_MAX_CHARS = 80
export const DEFAULT_TTS_POOL_WARM_WORKERS = 1
export const DEFAULT_TTS_POOL_MAX_WORKERS = 0
export const DEFAULT_TTS_POOL_AUTO_SCALE_ENABLED = true
export const DEFAULT_TTS_POOL_IDLE_TIMEOUT_MS = 60_000
export const DEFAULT_TTS_POOL_QUEUE_MAX_DEPTH = 8
export const DEFAULT_TTS_POOL_QUEUE_TIMEOUT_MS = 15_000
export const DEFAULT_TTS_POOL_EXECUTION_TIMEOUT_MS = 30_000
export const DEFAULT_TTS_WORKER_RECYCLE_AFTER_JOBS = 0
export const DEFAULT_QUANTIZATION = "int8"
export const WAKE_WORD_ENGINE_ENUM = {
	KWS: "KWS",
} as const
export const WAKE_WORD_ENGINE_ENUM_VALUES = [WAKE_WORD_ENGINE_ENUM.KWS] as const
export const STT_ENGINE_ENUM = {
	WHISPER: "WHISPER",
	MOONSHINE: "MOONSHINE",
	ZIPFORMER: "ZIPFORMER",
	PARAKEET: "PARAKEET",
	STREAMING_TRANSDUCER: "STREAMING_TRANSDUCER",
	NEMOTRON_STREAMING: "NEMOTRON_STREAMING",
	OPENAI_COMPATIBLE: "OPENAI_COMPATIBLE",
	NEMO_SPEECH: "NEMO_SPEECH",
} as const
export const STT_ENGINE_ENUM_VALUES = [
	STT_ENGINE_ENUM.WHISPER,
	STT_ENGINE_ENUM.MOONSHINE,
	STT_ENGINE_ENUM.ZIPFORMER,
	STT_ENGINE_ENUM.PARAKEET,
	STT_ENGINE_ENUM.STREAMING_TRANSDUCER,
	STT_ENGINE_ENUM.NEMOTRON_STREAMING,
	STT_ENGINE_ENUM.OPENAI_COMPATIBLE,
	STT_ENGINE_ENUM.NEMO_SPEECH,
] as const
export const LLM_ENGINE_ENUM = {
	OLLAMA: "OLLAMA",
	OPENAI_COMPATIBLE: "OPENAI_COMPATIBLE",
} as const
export const LLM_ENGINE_ENUM_VALUES = [
	LLM_ENGINE_ENUM.OLLAMA,
	LLM_ENGINE_ENUM.OPENAI_COMPATIBLE,
] as const
export const REASONING_EFFORT_ENUM = {
	NONE: "none",
	LOW: "low",
	MEDIUM: "medium",
	HIGH: "high",
} as const
export const REASONING_EFFORT_ENUM_VALUES = [
	REASONING_EFFORT_ENUM.NONE,
	REASONING_EFFORT_ENUM.LOW,
	REASONING_EFFORT_ENUM.MEDIUM,
	REASONING_EFFORT_ENUM.HIGH,
] as const
export const DEFAULT_REASONING_EFFORT = REASONING_EFFORT_ENUM.NONE
export const DEFAULT_REFLECTION_REASONING_EFFORT = REASONING_EFFORT_ENUM.NONE
export const TTS_ENGINE_ENUM = {
	KOKORO: "KOKORO",
	POCKET: "POCKET",
	VITS: "VITS",
	KITTEN: "KITTEN",
	MATCHA: "MATCHA",
	SUPERTONIC: "SUPERTONIC",
} as const
export const TTS_ENGINE_ENUM_VALUES = [
	TTS_ENGINE_ENUM.KOKORO,
	TTS_ENGINE_ENUM.POCKET,
	TTS_ENGINE_ENUM.VITS,
	TTS_ENGINE_ENUM.KITTEN,
	TTS_ENGINE_ENUM.MATCHA,
	TTS_ENGINE_ENUM.SUPERTONIC,
] as const
export const WAKE_WORD_FRAMEWORK_ENUM = {
	ONNX: "onnx",
} as const
export const WAKE_WORD_FRAMEWORK_ENUM_VALUES = [
	WAKE_WORD_FRAMEWORK_ENUM.ONNX,
] as const
