export const DEFAULT_SATELLITE_SPECULATION_ENABLED = false
export const DEFAULT_PLAYBACK_PAUSE_ENABLED = false
export const DEFAULT_WORD_LEVEL_HEARD_ENABLED = false
export const DEFAULT_HEARD_SILENCE_TRIM_ENABLED = true
export const DEFAULT_HEARD_SILENCE_RMS = 0.01
export const DEFAULT_GRPC_UNARY_DEADLINE_MS = 10_000
export const DEFAULT_GRPC_STREAM_IDLE_TIMEOUT_MS = 15_000
export const DEFAULT_GRPC_STREAM_DEADLINE_MS = 60_000
export const DEFAULT_PEER_STALE_AFTER_MS = 90_000
export const DEFAULT_CONFIG_RELOAD_DRAIN_MS = 5_000
export const DEFAULT_MODEL_INSTALL_ALLOWED_HOSTS: string[] = [
	"huggingface.co",
	"hf.co",
	"github.com",
	"objects.githubusercontent.com",
]
export const DEFAULT_HEARTBEAT_SIGNATURE_REQUIRED = true
export const DEFAULT_MESH_SECRET_GRACE_MS = 86_400_000
export const DEFAULT_GRPC_TLS = false
export const DEFAULT_SATELLITE_WYOMING_STREAMING_TTS = true
export const DEFAULT_AUDIO_PLAYBACK_VOLUME = 100
export const DEFAULT_AUDIO_PLAYBACK_STREAMING_ENABLED = true
export const DEFAULT_PLAYBACK_WATCHDOG_GRACE_MS = 2500
export const DEFAULT_PLAYBACK_TRUNCATION_REPLAY_ENABLED = true
export const DEFAULT_PLAYBACK_TRUNCATION_REPLAY_THRESHOLD_MS = 750
export const DEFAULT_FEEDBACK_SOUNDS_ENABLED = true
export const DEFAULT_ACK_SOUND_ENABLED = true
export const DEFAULT_ERROR_SOUND_ENABLED = true
export const DEFAULT_DONE_SOUND_ENABLED = true
export const DEFAULT_THINKING_SOUND_ENABLED = false
export const DEFAULT_ENDPOINT_SOUND_ENABLED = false
export const DEFAULT_ACK_SOUND_PATH = "data/sounds/ack.wav"
export const DEFAULT_ERROR_SOUND_PATH = "data/sounds/error.wav"
export const DEFAULT_DONE_SOUND_PATH = "data/sounds/done.wav"
export const DEFAULT_THINKING_SOUND_PATH = "data/sounds/thinking.wav"
export const DEFAULT_ENDPOINT_SOUND_PATH = "data/sounds/endpoint.wav"
export const AUDIO_PLAYBACK_ENGINE_ENUM = {
	SOX: "SOX",
	PLAY_SOUND: "PLAY-SOUND",
} as const
export const AUDIO_PLAYBACK_ENGINE_ENUM_VALUES = [
	AUDIO_PLAYBACK_ENGINE_ENUM.SOX,
	AUDIO_PLAYBACK_ENGINE_ENUM.PLAY_SOUND,
] as const
export const MQTT_TYPE_ENUM = {
	LOCAL: "LOCAL",
} as const
export const MQTT_TYPE_ENUM_VALUES = [MQTT_TYPE_ENUM.LOCAL] as const
export const MQTT_PROTOCOL_ENUM = {
	MQTT: "mqtt",
	MQTTS: "mqtts",
	WS: "ws",
	WSS: "wss",
} as const
export const MQTT_PROTOCOL_ENUM_VALUES = [
	MQTT_PROTOCOL_ENUM.MQTT,
	MQTT_PROTOCOL_ENUM.MQTTS,
	MQTT_PROTOCOL_ENUM.WS,
	MQTT_PROTOCOL_ENUM.WSS,
] as const
export const SATELLITE_PROTOCOL_ENUM = {
	NATIVE: "native",
	WYOMING: "wyoming",
	ESPHOME: "esphome",
	LIVEKIT: "livekit",
	OPENAI_REALTIME: "openai-realtime",
} as const
export const SATELLITE_PROTOCOL_ENUM_VALUES = [
	SATELLITE_PROTOCOL_ENUM.NATIVE,
	SATELLITE_PROTOCOL_ENUM.WYOMING,
	SATELLITE_PROTOCOL_ENUM.ESPHOME,
	SATELLITE_PROTOCOL_ENUM.LIVEKIT,
	SATELLITE_PROTOCOL_ENUM.OPENAI_REALTIME,
] as const
export const DEFAULT_SATELLITE_PROTOCOL = SATELLITE_PROTOCOL_ENUM.ESPHOME
export const DEFAULT_SATELLITE_PORT = 6053
export const DEFAULT_WYOMING_PORT = 10700
export const DEFAULT_LIVEKIT_PORT = 7880
export const DEFAULT_SATELLITE_PORT_BY_PROTOCOL: Record<
	(typeof SATELLITE_PROTOCOL_ENUM_VALUES)[number],
	number
> = {
	[SATELLITE_PROTOCOL_ENUM.ESPHOME]: DEFAULT_SATELLITE_PORT,
	[SATELLITE_PROTOCOL_ENUM.NATIVE]: DEFAULT_SATELLITE_PORT,
	[SATELLITE_PROTOCOL_ENUM.WYOMING]: DEFAULT_WYOMING_PORT,
	[SATELLITE_PROTOCOL_ENUM.LIVEKIT]: DEFAULT_LIVEKIT_PORT,
	[SATELLITE_PROTOCOL_ENUM.OPENAI_REALTIME]: DEFAULT_SATELLITE_PORT,
}
export const DEFAULT_SATELLITE_ACTIVE = true
export const VOLUME_PERCENT_SCALE = 100
export const DEFAULT_ESPHOME_DISCOVERY_MS = 4000
export const DEFAULT_PROVIDER_DISCOVERY_MS = 4000
export const DEFAULT_SATELLITE_RECONNECT_MS = 5000
export const DEFAULT_SATELLITE_LIVENESS_PING_MS = 15_000
export const DEFAULT_SATELLITE_LIVENESS_TIMEOUT_MS = 45_000
export const DEFAULT_SATELLITE_RECONNECT_MAX_MS = 60_000
export const DEFAULT_SATELLITE_RECONNECT_JITTER = 0.3
export const DEFAULT_SATELLITE_TURN_TIMEOUT_MS = 120_000
export const DEFAULT_DESIRED_WAKE_WORDS: string[] = []
export const DEFAULT_SATELLITE_DESIRED_NUMBERS: Record<string, number> = {}
export const DEFAULT_SATELLITE_FOLLOW_UP = true
export const DEFAULT_SATELLITE_FOLLOW_UP_NO_SPEECH_MS = 8000
export const DEFAULT_SATELLITE_PLAYBACK_DRAIN_MARGIN_MS = 250
export const DEFAULT_SATELLITE_RUN_LISTENING_MAX_MS = 20000
export const DEFAULT_SATELLITE_FOLLOW_UP_REQUEST_MAX_MS = 5000
export const DEFAULT_SATELLITE_CAPTURE_HEAD_TRIM_MS = 0
export const ANNOUNCEMENT_KIND_ENUM = {
	TEXT: "text",
	AUDIO: "audio",
} as const
export const ANNOUNCEMENT_KIND_ENUM_VALUES = [
	ANNOUNCEMENT_KIND_ENUM.TEXT,
	ANNOUNCEMENT_KIND_ENUM.AUDIO,
] as const
export const ANNOUNCEMENT_DELIVERY_ENUM = {
	ORIGINAL: "original",
	DOMIA_VOICE: "domia-voice",
} as const
export const ANNOUNCEMENT_DELIVERY_ENUM_VALUES = [
	ANNOUNCEMENT_DELIVERY_ENUM.ORIGINAL,
	ANNOUNCEMENT_DELIVERY_ENUM.DOMIA_VOICE,
] as const
export const DEFAULT_ANNOUNCEMENT_MAX_AGE_MS = 7 * 86_400_000
export const DEFAULT_MQTT_HOST = "localhost"
export const DEFAULT_MQTT_USERNAME = "domia"
export const DEFAULT_MQTT_PASSWORD = "domia"
export const DEFAULT_MQTT_TOPIC_ROOT = "domia"
export const DEFAULT_MQTT_PORT = 1883
export const DEFAULT_MQTT_QOS = 1
export const DEFAULT_PROACTIVITY_ENGINE = false
export const DEFAULT_PROACTIVE_IDLE_NUDGE_ENABLED = false
export const DEFAULT_PROACTIVE_IDLE_NUDGE_AFTER_MS = 1_800_000
export const DEFAULT_PROACTIVE_IDLE_NUDGE_MIN_INTERVAL_MS = 3_600_000
export const DEFAULT_PROACTIVE_MAX_PER_HOUR = 6
export const DEFAULT_PROACTIVE_MAX_PER_DAY = 20
export const DEFAULT_PROACTIVE_CHIME_ENABLED = true
export const DEFAULT_PROACTIVE_DEFER_MAX_MS = 15_000
export const DEFAULT_PROACTIVE_CRITICAL_DEFER_MAX_MS = 300_000
export const DEFAULT_PROACTIVE_TICK_MS = 5_000
export const DEFAULT_PROACTIVE_LEASE_MS = 60_000
export const DEFAULT_PROACTIVE_MAX_ATTEMPTS = 3
export const DEFAULT_PROACTIVE_RETRY_BACKOFF_MS = 30_000
export const PROACTIVE_VERB_ENUM = {
	ANNOUNCE: "announce",
	CONVERSE: "converse",
} as const
export const PROACTIVE_VERB_ENUM_VALUES = [
	PROACTIVE_VERB_ENUM.ANNOUNCE,
	PROACTIVE_VERB_ENUM.CONVERSE,
] as const
export const DEFAULT_PROACTIVE_VERB = PROACTIVE_VERB_ENUM.ANNOUNCE
export const PROACTIVE_IMPORTANCE_ENUM = {
	CRITICAL: "critical",
	NORMAL: "normal",
	AMBIENT: "ambient",
} as const
export const PROACTIVE_IMPORTANCE_ENUM_VALUES = [
	PROACTIVE_IMPORTANCE_ENUM.CRITICAL,
	PROACTIVE_IMPORTANCE_ENUM.NORMAL,
	PROACTIVE_IMPORTANCE_ENUM.AMBIENT,
] as const
export const DEFAULT_PROACTIVE_IMPORTANCE = PROACTIVE_IMPORTANCE_ENUM.NORMAL
export const PROACTIVE_SCHEDULE_STATUS_ENUM = {
	PENDING: "pending",
	LEASED: "leased",
	DONE: "done",
	CANCELLED: "cancelled",
	FAILED: "failed",
} as const
export const PROACTIVE_SCHEDULE_STATUS_ENUM_VALUES = [
	PROACTIVE_SCHEDULE_STATUS_ENUM.PENDING,
	PROACTIVE_SCHEDULE_STATUS_ENUM.LEASED,
	PROACTIVE_SCHEDULE_STATUS_ENUM.DONE,
	PROACTIVE_SCHEDULE_STATUS_ENUM.CANCELLED,
	PROACTIVE_SCHEDULE_STATUS_ENUM.FAILED,
] as const
export const PROACTIVE_TARGET_KIND_ENUM = {
	AUTO: "auto",
	LOCAL: "local",
	SATELLITE: "satellite",
} as const
export const PROACTIVE_TARGET_KIND_ENUM_VALUES = [
	PROACTIVE_TARGET_KIND_ENUM.AUTO,
	PROACTIVE_TARGET_KIND_ENUM.LOCAL,
	PROACTIVE_TARGET_KIND_ENUM.SATELLITE,
] as const
export const DEFAULT_PROACTIVE_TARGET_KIND = PROACTIVE_TARGET_KIND_ENUM.AUTO
export const DEFAULT_MESH_CONTROL_TOLERANCE_MS = 30_000
export const DEFAULT_MESH_DROP_WARN_WINDOW_MS = 10_000
export const DEFAULT_MODEL_DOWNLOAD_TIMEOUT_MS = 1_800_000
export const DEFAULT_MODEL_INSTALL_MAX_BYTES = 12 * 1024 * 1024 * 1024
export const DEFAULT_MODEL_INSTALL_MAX_REDIRECTS = 5
export const DEFAULT_MODEL_INSTALL_MAX_CONCURRENT_JOBS = 2
export const DEFAULT_MODEL_JOB_RETENTION_MS = 1_800_000
export const DEFAULT_PUBLIC_AUDIO_BASE_URL: string | null = null
