export const SKILL_PROTOCOL_ENUM = {
	MCP: "mcp",
	HTTP: "http",
	MQTT: "mqtt",
	BUILTIN: "builtin",
} as const
export const SKILL_PROTOCOL_ENUM_VALUES = [
	SKILL_PROTOCOL_ENUM.MCP,
	SKILL_PROTOCOL_ENUM.HTTP,
	SKILL_PROTOCOL_ENUM.MQTT,
	SKILL_PROTOCOL_ENUM.BUILTIN,
] as const
export const BUILTIN_PROVIDER_NAME = "domia"
export const BUILTIN_PROVIDER_URL = "builtin://localhost/domia"
export const BUILTIN_PROVIDER_ID_PREFIX = "builtin:"
export const ROUTINE_MAX_STEPS = 8
export const ROUTINE_TOOL_PREFIX = "routine_"
export const ROUTINE_SLUG_PATTERN = /^[a-z0-9_]{1,40}$/
export const DEFAULT_FAST_PATH_DURATION_MAX_SECONDS = 86_400
export const FAST_PATH_SKIP_PHRASES_PER_SIDE = 3
export const FAST_PATH_COMPOUND_MAX_LEADING_STOPWORDS = 2
export const FAST_PATH_CLOCK_NIGHT_PM_FROM_HOUR = 5
export const MCP_TRANSPORT_ENUM = {
	HTTP: "http",
	SSE: "sse",
	STDIO: "stdio",
} as const
export const MCP_TRANSPORT_ENUM_VALUES = [
	MCP_TRANSPORT_ENUM.HTTP,
	MCP_TRANSPORT_ENUM.SSE,
	MCP_TRANSPORT_ENUM.STDIO,
] as const
export const MCP_PROTOCOL_MODE_ENUM = {
	LEGACY: "legacy",
	AUTO: "auto",
	MODERN: "2026-07-28",
} as const
export const MCP_PROTOCOL_MODE_ENUM_VALUES = [
	MCP_PROTOCOL_MODE_ENUM.LEGACY,
	MCP_PROTOCOL_MODE_ENUM.AUTO,
	MCP_PROTOCOL_MODE_ENUM.MODERN,
] as const
export const SKILL_TRUST_TIER_ENUM = {
	TRUSTED: "trusted",
	STANDARD: "standard",
	UNTRUSTED: "untrusted",
} as const
export const SKILL_TRUST_TIER_ENUM_VALUES = [
	SKILL_TRUST_TIER_ENUM.TRUSTED,
	SKILL_TRUST_TIER_ENUM.STANDARD,
	SKILL_TRUST_TIER_ENUM.UNTRUSTED,
] as const
export const DEFAULT_SKILL_TRUST_TIER = SKILL_TRUST_TIER_ENUM.UNTRUSTED
export const HINT_SOURCE_ENUM = {
	DESCRIPTOR: "descriptor",
	ANNOTATION: "annotation",
	DEFAULT: "default",
} as const
export const ARG_NORMALIZE_OP_ENUM = {
	TRIM: "trim",
	LOWERCASE: "lowercase",
	UPPERCASE: "uppercase",
	COLLAPSE_SPACES: "collapseSpaces",
	NUMBER: "number",
	INTEGER: "integer",
	BOOLEAN: "boolean",
	STRING: "string",
	STRING_LIST: "stringList",
	STRIP_UNITS: "stripUnits",
	PERCENT_TO_FRACTION: "percentToFraction",
	FRACTION_TO_PERCENT: "fractionToPercent",
	FAHRENHEIT_TO_CELSIUS: "fahrenheitToCelsius",
	CELSIUS_TO_FAHRENHEIT: "celsiusToFahrenheit",
} as const
export const ARG_NORMALIZE_OP_ENUM_VALUES = [
	ARG_NORMALIZE_OP_ENUM.TRIM,
	ARG_NORMALIZE_OP_ENUM.LOWERCASE,
	ARG_NORMALIZE_OP_ENUM.UPPERCASE,
	ARG_NORMALIZE_OP_ENUM.COLLAPSE_SPACES,
	ARG_NORMALIZE_OP_ENUM.NUMBER,
	ARG_NORMALIZE_OP_ENUM.INTEGER,
	ARG_NORMALIZE_OP_ENUM.BOOLEAN,
	ARG_NORMALIZE_OP_ENUM.STRING,
	ARG_NORMALIZE_OP_ENUM.STRING_LIST,
	ARG_NORMALIZE_OP_ENUM.STRIP_UNITS,
	ARG_NORMALIZE_OP_ENUM.PERCENT_TO_FRACTION,
	ARG_NORMALIZE_OP_ENUM.FRACTION_TO_PERCENT,
	ARG_NORMALIZE_OP_ENUM.FAHRENHEIT_TO_CELSIUS,
	ARG_NORMALIZE_OP_ENUM.CELSIUS_TO_FAHRENHEIT,
] as const
export const TOOL_RUN_STATUS_ENUM = {
	DISPATCHED: "dispatched",
	OK: "ok",
	FAILED: "failed",
	TIMEOUT: "timeout",
	CANCELLED: "cancelled",
	DENIED: "denied",
	LOST: "lost",
} as const
export const TOOL_RUN_STATUS_ENUM_VALUES = [
	TOOL_RUN_STATUS_ENUM.DISPATCHED,
	TOOL_RUN_STATUS_ENUM.OK,
	TOOL_RUN_STATUS_ENUM.FAILED,
	TOOL_RUN_STATUS_ENUM.TIMEOUT,
	TOOL_RUN_STATUS_ENUM.CANCELLED,
	TOOL_RUN_STATUS_ENUM.DENIED,
	TOOL_RUN_STATUS_ENUM.LOST,
] as const
export const ASYNC_FOLLOW_UP_POLICY_ENUM = {
	QUEUE: "queue",
	DROP: "drop",
} as const
export const ASYNC_FOLLOW_UP_POLICY_ENUM_VALUES = [
	ASYNC_FOLLOW_UP_POLICY_ENUM.QUEUE,
	ASYNC_FOLLOW_UP_POLICY_ENUM.DROP,
] as const
export const DEFAULT_ASYNC_FOLLOW_UP_POLICY = ASYNC_FOLLOW_UP_POLICY_ENUM.QUEUE
export const DEFAULT_ASYNC_FOLLOW_UP_MAX_WAIT_MS = 15_000
export const DEFAULT_LLM_STREAM_IDLE_MS = 30000
export const DEFAULT_QUIET_AUDIO_POLL_MS = 250
export const DEFAULT_QUIET_AUDIO_DEADLINE_MS = 20000
export const DEFAULT_AGENT_REPEAT_WARN_AT = 1
export const DEFAULT_AGENT_REPEAT_BLOCK_AT = 2
export const DEFAULT_AGENT_MAX_TOOL_CALLS_PER_TURN = 6
export const DEFAULT_AGENT_RECENT_TOOLS_TURNS = 2
export const DEFAULT_ANAPHORA_MAX_AGE_MS = 120_000
export const DEFAULT_FAST_PATH_ENABLED = true
export const DEFAULT_FAST_PATH_MIN_COVERAGE = 0.1
export const DEFAULT_FAST_PATH_MAX_UTTERANCE_CHARS = 80
export const DEFAULT_FAST_PATH_BLOCKLIST_ENABLED = true
export const DEFAULT_SKILL_MAX_LIST_PAGES = 20
export const DEFAULT_SKILL_MAX_LISTED_TOOLS = 500
export const DEFAULT_SKILL_MAX_TOTAL_TIMEOUT_MS = 30_000
export const DEFAULT_CONSTRAINED_REPAIR_ENABLED = true
export const DEFAULT_SLOT_WAIT_TIMEOUT_MS = 8000
export const DEFAULT_SLOT_WAIT_POLL_MS = 25
export const DEFAULT_INTENT_LLM_ON_SINGLE_SLOT = true
export const AGENT_DECISION_MODE_ENUM = {
	NATIVE: "native",
	STRUCTURED: "structured",
} as const
export const AGENT_DECISION_MODE_ENUM_VALUES = [
	AGENT_DECISION_MODE_ENUM.NATIVE,
	AGENT_DECISION_MODE_ENUM.STRUCTURED,
] as const
export const DEFAULT_AGENT_DECISION_MODE = AGENT_DECISION_MODE_ENUM.NATIVE
export const DEFAULT_AUTHORED_SPEECH_ENABLED = false
export const AGENT_PROMPT_MODE_ENUM = {
	LEAN: "lean",
	COMPACT: "compact",
	FULL: "full",
} as const
export const AGENT_PROMPT_MODE_ENUM_VALUES = [
	AGENT_PROMPT_MODE_ENUM.LEAN,
	AGENT_PROMPT_MODE_ENUM.COMPACT,
	AGENT_PROMPT_MODE_ENUM.FULL,
] as const
export const DEFAULT_AGENT_PROMPT_MODE = AGENT_PROMPT_MODE_ENUM.COMPACT
export const SKILLS_ROUTING_ENUM = {
	ALWAYS_AGENT: "always-agent",
	INTENT_GATE: "intent-gate",
	EMBEDDING_GATE: "embedding-gate",
	FAST_ROUTER: "fast-router",
} as const
export const SKILLS_ROUTING_ENUM_VALUES = [
	SKILLS_ROUTING_ENUM.ALWAYS_AGENT,
	SKILLS_ROUTING_ENUM.INTENT_GATE,
	SKILLS_ROUTING_ENUM.EMBEDDING_GATE,
	SKILLS_ROUTING_ENUM.FAST_ROUTER,
] as const
export const DEFAULT_SKILLS_ROUTING = SKILLS_ROUTING_ENUM.EMBEDDING_GATE
export const DEFAULT_INTENT_MODEL = "llama3.2:3b"
export const DEFAULT_EMBEDDING_MODEL = "nomic-embed-text"
export const DEFAULT_INTENT_EMBED_THRESHOLD = 0.66
export const DEFAULT_INTENT_LEXICAL_MIN_SCORE = 2
export const DEFAULT_INTENT_CACHE_ENABLED = true
export const DEFAULT_INTENT_CACHE_SIZE = 256
export const DEFAULT_INTENT_CACHE_MIN_SIMILARITY = 0.97
export const DEFAULT_DESCRIPTOR_ROUTING_ENABLED = true
export const DEFAULT_EMBED_MODEL_PATH = "data/models/bge-small-en-v1.5"
export const MATCHER_ENGINE_ENUM = {
	LEXICAL: "lexical",
	SEMANTIC: "semantic",
	HYBRID: "hybrid",
} as const
export const MATCHER_ENGINE_ENUM_VALUES = [
	MATCHER_ENGINE_ENUM.LEXICAL,
	MATCHER_ENGINE_ENUM.SEMANTIC,
	MATCHER_ENGINE_ENUM.HYBRID,
] as const
export const DEFAULT_MATCHER_ENGINE = MATCHER_ENGINE_ENUM.HYBRID
export const DEFAULT_MATCHER_SEMANTIC_THRESHOLD = 0.55
export const DEFAULT_MATCHER_RRF_K = 60
export const DEFAULT_MATCHER_CASCADE_EXIT = 6
export const DEFAULT_LLM_SLOT_AFFINITY_ENABLED = false
export const EMBED_BACKEND_ENUM = {
	TRANSFORMERS: "transformers",
	OLLAMA: "ollama",
} as const
export const EMBED_BACKEND_ENUM_VALUES = [
	EMBED_BACKEND_ENUM.TRANSFORMERS,
	EMBED_BACKEND_ENUM.OLLAMA,
] as const
export const DEFAULT_EMBED_BACKEND = EMBED_BACKEND_ENUM.TRANSFORMERS
export const DEFAULT_SKILLS_ENGINE = true
export const DEFAULT_BUILTIN_TOOLS = true
export const DEFAULT_SKILL_PROTOCOL = SKILL_PROTOCOL_ENUM.MCP
export const DEFAULT_MCP_TRANSPORT_TYPE = MCP_TRANSPORT_ENUM.HTTP
export const DEFAULT_MCP_PROTOCOL_MODE = MCP_PROTOCOL_MODE_ENUM.LEGACY
export const DEFAULT_MCP_INPUT_REQUIRED_MAX_ROUNDS = 10
export const DEFAULT_SKILL_MAX_RESULT_CHARS = 4000
export const DEFAULT_SKILL_REFRESH_MS = 300_000
export const SKILL_TOOLS_TTL_FLOOR_MS = 5_000
export const DEFAULT_SKILL_LIST_CHANGED_DEBOUNCE_MS = 2_000
export const DEFAULT_SKILL_TIMEOUT_MS = 8000
export const DEFAULT_AGENT_MAX_STEPS = 5
export const DEFAULT_SLOW_TOOL_AFTER_MS = 1200
export const DEFAULT_AGENT_ACK_AFTER_MS = 600
export const DEFAULT_TOOL_SHORTLIST_MAX = 8
export const DEFAULT_SKILL_SERVE_STALE_TOOLS = false
export const DEFAULT_SKILL_RETRY_MAX_ATTEMPTS = 1
export const DEFAULT_SKILL_RETRY_BACKOFF_MS = 200
export const DEFAULT_SKILL_BREAKER_THRESHOLD = 3
export const DEFAULT_SKILL_BREAKER_COOLDOWN_MS = 30_000
export const DEFAULT_AGENT_BUDGET_MS = 15_000
export const DEFAULT_CONFIRMATION_TTL_MS = 120_000
export const DEFAULT_CONFIRMATION_EXPIRED_GRACE_MS = 30_000
export const DEFAULT_ELICIT_TTL_MS = 30_000
export const CONFIRMATION_STATUS_ENUM = {
	PENDING: "pending",
	APPROVED: "approved",
	DENIED: "denied",
	IGNORED: "ignored",
	EXPIRED: "expired",
	SUPERSEDED: "superseded",
} as const
export const CONFIRMATION_STATUS_ENUM_VALUES = [
	CONFIRMATION_STATUS_ENUM.PENDING,
	CONFIRMATION_STATUS_ENUM.APPROVED,
	CONFIRMATION_STATUS_ENUM.DENIED,
	CONFIRMATION_STATUS_ENUM.IGNORED,
	CONFIRMATION_STATUS_ENUM.EXPIRED,
	CONFIRMATION_STATUS_ENUM.SUPERSEDED,
] as const
export const DEFAULT_SKILL_IDEMPOTENT_WITHIN_TURN = false
export const DEFAULT_TOOL_CALL_TEMPERATURE = 0.2
export const DEFAULT_TOOL_CALL_NUM_PREDICT = 512
export const DEFAULT_TOOL_REQUEST_MAX_RETRIES = 0
export const DEFAULT_AGENT_QUESTION_GUARD_ENABLED = true
export const DEFAULT_AGENT_TARGET_GUARD_ENABLED = true
export const DEFAULT_AGENT_READ_THEN_ANSWER_ENABLED = true
export const DEFAULT_FAST_PATH_COMPOUND_ENABLED = true
export const DEFAULT_FAST_PATH_COMPOUND_MAX_TARGETS = 3
export const SKILL_TOOL_NAME_SEPARATOR = "__"
export const DEFAULT_FINALIZE_ACK = "Done."
export const DEFAULT_FINALIZE_ERROR = "Sorry, I couldn't do that."
export const SKILL_DESCRIPTOR_RESOURCE_URI = "domia://descriptor"
export const SKILL_SERVER_DESCRIPTOR_MAX_BYTES = 64 * 1024
export const SKILL_SERVER_DESCRIPTOR_MAX_TEMPLATES = 200
export const SKILL_SERVER_DESCRIPTOR_MAX_TEMPLATE_CHARS = 200
export const SKILL_SERVER_DESCRIPTOR_MAX_EXPANSION_RULES = 50
export const SKILL_SERVER_DESCRIPTOR_MAX_EXPANSION_DEPTH = 4
export const SKILL_SERVER_DESCRIPTOR_MAX_SLOT_VALUES = 50
export const SKILL_SERVER_DESCRIPTOR_MAX_FINALIZE_CHARS = 200
export const SKILL_SERVER_DESCRIPTOR_MAX_DESCRIPTION_CHARS = 500
export const SKILL_SERVER_DESCRIPTOR_ALLOWED_FIELDS = [
	"description",
	"routing.aliases",
	"routing.exampleUtterances",
	"routing.keywords",
	"execution.finalize",
	"execution.genericWords",
	"fastPath.intents[].tool",
	"fastPath.intents[].templates",
	"fastPath.intents[].slots (enum | map | schemaEnum | range | duration | clockTime)",
	"fastPath.intents[].requiredKeywords",
	"fastPath.intents[].argDefaults",
	"fastPath.intents[].priority",
	"fastPath.expansionRules",
	"i18n.<lang>.<same fields>",
] as const
export const SKILL_SERVER_DESCRIPTOR_STRIPPED_FIELDS = [
	"kind",
	"execution.coreTools",
	"execution.toolPolicy",
	"execution.toolHints",
	"execution.paramAllow",
	"execution.argNormalize",
	"execution.resilience",
	"execution.hiddenTools",
	"fastPath.intents[].allowBlockedTokens",
] as const
export const SKILL_SERVER_DESCRIPTOR_REJECTED_FIELDS = [
	"fastPath.intents[].slots.source.kind = context",
] as const
export const DEFAULT_TOOL_RUN_MAX_AGE_MS = 30 * 86_400_000
export const DEFAULT_TOOL_RUN_MAX_ROWS_PER_DOMIA = 5_000
export const DEFAULT_SETTLED_CONFIRMATION_MAX_AGE_MS = 7 * 86_400_000
