export const DEFAULT_LANGUAGE = "en"
export const DEFAULT_IS_HOSTED = false
export const DEFAULT_MEMORY_WINDOW_TURNS = 8
export const DEFAULT_MEMORY_MAX_AGE_MS = 1_800_000
export const DEFAULT_LLM_CONCURRENCY = 3
export const DEFAULT_REFLECTION_ONLY_WHEN_IDLE = true
export const DEFAULT_ENVIRONMENT_TIME_ENABLED = true
export const DEFAULT_REFLECTION_CONCURRENCY = 2
export const DEFAULT_REFLECTION_QUEUE_MAX_DEPTH = 4
export const DEFAULT_REFLECTION_YIELD_TO_VOICE = true
export const DEFAULT_MAX_CONCURRENT_VOICE_REPLIES = 1
export const DEFAULT_MAX_QUEUED_VOICE_REPLIES = 4
export const DEFAULT_VOICE_QUEUE_TIMEOUT_MS = 15_000
export const DEFAULT_OWN_CONFIG_TTL_MS = 30_000
export const DEFAULT_WARMUP_ON_BOOT = true
export const DEFAULT_WAKE_WORD = "computer"
export const DEFAULT_WAKE_WORD_MODEL = "kws-zipformer-gigaspeech"
export const DEFAULT_WAKE_WORD_MODEL_PATH =
	"data/models/kws-zipformer-gigaspeech-3.3M-2024-01-01"
export const VAD_ENGINE_ENUM = {
	SILERO: "SILERO",
} as const
export const VAD_ENGINE_ENUM_VALUES = [VAD_ENGINE_ENUM.SILERO] as const
export const DEFAULT_VAD_ENGINE = VAD_ENGINE_ENUM.SILERO
export const DEFAULT_VAD_MODEL_PATH = "data/models/silero_vad.onnx"
export const DEFAULT_WAKE_WORD_SENSITIVITY = 1.0
export const DEFAULT_WAKE_WORD_THRESHOLD = 0.25
export const DEFAULT_WAKE_WORD_COOLDOWN_S = 2.0
export const DEFAULT_WAKE_WORD_NUM_THREADS = 1
export const DEFAULT_WAKE_WORD_PROVIDER = "cpu"
export const DEFAULT_VAD_THRESHOLD = 0.5
export const DEFAULT_VAD_MIN_SILENCE_S = 0.5
export const DEFAULT_VAD_END_OF_SPEECH_MS = 200
export const DEFAULT_FOLLOW_UP_WINDOW_MS = 8000
export const DEFAULT_BARGE_IN_ENABLED = true
export const DEFAULT_SPECULATIVE_SILENCE_MS = 300
export const DEFAULT_SEMANTIC_ENDPOINTING_ENABLED = false
export const DEFAULT_ACOUSTIC_ENDPOINTING_ENABLED = false
export const DEFAULT_ACOUSTIC_ENDPOINT_THRESHOLD = 0.5
export const TURN_DETECTOR_ENGINE_ENUM = {
	SMART_TURN: "SMART_TURN",
} as const
export const TURN_DETECTOR_ENGINE_ENUM_VALUES = [
	TURN_DETECTOR_ENGINE_ENUM.SMART_TURN,
] as const
export const DEFAULT_TURN_DETECTOR_ENGINE = TURN_DETECTOR_ENGINE_ENUM.SMART_TURN
export const DEFAULT_TURN_DETECTOR_MODEL_PATH =
	"data/models/smart-turn/smart-turn-v3.2-cpu.onnx"
export const DEFAULT_SPECULATIVE_TTS_ENABLED = false
export const DEFAULT_SPECULATE_WITH_SKILLS = false
export const DEFAULT_SPECULATION_SKILL_GATE_MAX_SCORE = 0
export const DEFAULT_SHARED_MIC_STREAM_ENABLED = false
export const DEFAULT_ENDPOINT_COMPLETE_MS = 350
export const DEFAULT_DYNAMIC_ENDPOINTING_ENABLED = false
export const DEFAULT_DYNAMIC_ENDPOINT_MIN_MS = 300
export const DEFAULT_DYNAMIC_ENDPOINT_MAX_MS = 1500
export const DEFAULT_DYNAMIC_ENDPOINT_ALPHA = 0.9
export const DEFAULT_DYNAMIC_ENDPOINT_MARGIN = 1.5
export const DEFAULT_PAUSE_BARGE_IN_ENABLED = false
export const DEFAULT_FALSE_INTERRUPTION_TIMEOUT_MS = 2000
export const DEFAULT_PLAYBACK_PAUSE_ENABLED = false
export const DEFAULT_WORD_LEVEL_HEARD_ENABLED = false
export const DEFAULT_TTS_PACER_ENABLED = false
export const DEFAULT_TTS_PACER_MIN_REMAINING_MS = 5000
export const DEFAULT_TTS_PACER_MAX_CHARS = 300
export const DEFAULT_ECHO_SUPPRESS_ENABLED = false
export const DEFAULT_ECHO_SUPPRESS_MARGIN_MS = 500
export const DEFAULT_ENDPOINT_INCOMPLETE_MS = 900
export const DEFAULT_ENDPOINT_WAIT_MS = 1400
export const DEFAULT_FOLLOW_UP_LEAD_PAD_MS = 300
export const DEFAULT_SENTENCE_SOFT_FLUSH_MIN_CHARS = 20
export const DEFAULT_SENTENCE_FIRST_UNIT_MAX_WORDS = 8
export const DEFAULT_SENTENCE_MEDIUM_FLUSH_CHARS = 60
export const DEFAULT_SENTENCE_HARD_FLUSH_CHARS = 200
export const DEFAULT_SENTENCE_FIRST_FLUSH_MAX_MS = 800
export const DEFAULT_PIPELINE_MAX_QUEUE_DEPTH = 4
export const DEFAULT_PIPELINE_EAGER_TTS_SENTENCES = 2
export const DEFAULT_GRPC_UNARY_DEADLINE_MS = 10_000
export const DEFAULT_GRPC_STREAM_IDLE_TIMEOUT_MS = 15_000
export const DEFAULT_GRPC_STREAM_DEADLINE_MS = 60_000
export const DEFAULT_PEER_STALE_AFTER_MS = 90_000
export const DEFAULT_CONFIG_RELOAD_DRAIN_MS = 5_000
export const DEFAULT_AUDIO_CAPTURE_SAMPLE_RATE = 16000
export const DEFAULT_AUDIO_CAPTURE_BITS_PER_SAMPLE = 16
export const DEFAULT_AUDIO_CAPTURE_CHANNELS = 1
export const DEFAULT_AUDIO_CAPTURE_MAX_RECORDING_MS = 15000
export const DEFAULT_LLM_MODEL_TEMPERATURE = 0.7
export const DEFAULT_LLM_MODEL_CONTEXT_WINDOW = 4096
export const DEFAULT_LLM_MODEL_NUM_PREDICT = 80
export const DEFAULT_STT_MODEL_NAME = "parakeet-tdt-06b-v2"
export const DEFAULT_STT_MODEL_PATH = "data/models/parakeet-tdt-06b-v2"
export const DEFAULT_STT_ENABLE_ENDPOINT = true
export const DEFAULT_STT_RULE1_MIN_TRAILING_SILENCE = 1.2
export const DEFAULT_STT_RULE2_MIN_TRAILING_SILENCE = 0.6
export const DEFAULT_STT_RULE3_MIN_UTTERANCE_LENGTH = 12
export const DEFAULT_STT_NUM_THREADS = 2
export const DEFAULT_STT_PROVIDER = "cpu"
export const DEFAULT_STT_DECODE_PADDING_MS = 600
export const DEFAULT_STT_POOL_WARM_WORKERS = 1
export const DEFAULT_STT_POOL_MAX_WORKERS = 0
export const DEFAULT_STT_POOL_AUTO_SCALE_ENABLED = true
export const DEFAULT_STT_POOL_IDLE_TIMEOUT_MS = 60_000
export const DEFAULT_STT_POOL_QUEUE_MAX_DEPTH = 8
export const DEFAULT_STT_POOL_QUEUE_TIMEOUT_MS = 15_000
export const DEFAULT_STT_POOL_EXECUTION_TIMEOUT_MS = 30_000
export const DEFAULT_STT_MAX_CONCURRENT_STREAMING_SESSIONS = 0
export const DEFAULT_STT_SESSION_IDLE_TIMEOUT_MS = 10_000
export const DEFAULT_STT_WORKER_RECYCLE_AFTER_JOBS = 0
export const DEFAULT_LLM_MODEL_NAME = "llama3.2:3b"
export const DEFAULT_OLLAMA_HOST = "http://localhost:11434"
export const DEFAULT_OLLAMA_KEEP_ALIVE_MS = -1
export const DEFAULT_TTS_VOICE_NAME = "af_heart"
export const DEFAULT_TTS_MODEL_PATH = "data/models/kokoro-multi-lang-v1_0"
export const DEFAULT_POCKET_MODEL_PATH =
	"data/models/sherpa-onnx-pocket-tts-int8-2026-01-26"
export const DEFAULT_POCKET_NUM_STEPS = 5
export const DEFAULT_POCKET_REFERENCE_WAV = "test_wavs/bria.wav"
export const DEFAULT_POCKET_VOICE_CACHE = 50
export const DEFAULT_TTS_NUM_THREADS = 2
export const DEFAULT_TTS_PROVIDER = "cpu"
export const DEFAULT_TTS_MAX_NUM_SENTENCES = 1
export const DEFAULT_TTS_SILENCE_SCALE = 0.2
export const DEFAULT_TTS_SPEED = 1.0
export const DEFAULT_TTS_STREAMING_ENABLED = true
export const DEFAULT_TTS_POOL_WARM_WORKERS = 1
export const DEFAULT_TTS_POOL_MAX_WORKERS = 0
export const DEFAULT_TTS_POOL_AUTO_SCALE_ENABLED = true
export const DEFAULT_TTS_POOL_IDLE_TIMEOUT_MS = 60_000
export const DEFAULT_TTS_POOL_QUEUE_MAX_DEPTH = 8
export const DEFAULT_TTS_POOL_QUEUE_TIMEOUT_MS = 15_000
export const DEFAULT_TTS_POOL_EXECUTION_TIMEOUT_MS = 30_000
export const DEFAULT_TTS_WORKER_RECYCLE_AFTER_JOBS = 0
export const DEFAULT_AUDIO_PLAYBACK_VOLUME = 100
export const DEFAULT_AUDIO_PLAYBACK_STREAMING_ENABLED = true
export const DEFAULT_PLAYBACK_WATCHDOG_GRACE_MS = 2500
export const DEFAULT_PLAYBACK_TRUNCATION_REPLAY_ENABLED = true
export const DEFAULT_PLAYBACK_TRUNCATION_REPLAY_THRESHOLD_MS = 750
export const DEFAULT_FEEDBACK_SOUNDS_ENABLED = true
export const DEFAULT_ACK_SOUND_ENABLED = true
export const DEFAULT_ERROR_SOUND_ENABLED = true
export const DEFAULT_DONE_SOUND_ENABLED = true
export const DEFAULT_THINKING_SOUND_ENABLED = false
export const DEFAULT_ACK_SOUND_PATH = "data/sounds/ack.wav"
export const DEFAULT_ERROR_SOUND_PATH = "data/sounds/error.wav"
export const DEFAULT_DONE_SOUND_PATH = "data/sounds/done.wav"
export const DEFAULT_THINKING_SOUND_PATH = "data/sounds/thinking.wav"
export const DEFAULT_QUANTIZATION = "int8"

export const PERSONALITY_ENUM = {
	OPTIMISTIC: "OPTIMISTIC",
	CALM: "CALM",
	ANALYTICAL: "ANALYTICAL",
	EMPATHETIC: "EMPATHETIC",
	NEUTRAL: "NEUTRAL",
	PLAYFUL: "PLAYFUL",
	CAUTIOUS: "CAUTIOUS",
	ADAPTIVE: "ADAPTIVE",
	CUSTOM: "CUSTOM",
} as const
export const PERSONALITY_ENUM_VALUES = [
	PERSONALITY_ENUM.OPTIMISTIC,
	PERSONALITY_ENUM.CALM,
	PERSONALITY_ENUM.ANALYTICAL,
	PERSONALITY_ENUM.EMPATHETIC,
	PERSONALITY_ENUM.NEUTRAL,
	PERSONALITY_ENUM.PLAYFUL,
	PERSONALITY_ENUM.CAUTIOUS,
	PERSONALITY_ENUM.ADAPTIVE,
	PERSONALITY_ENUM.CUSTOM,
] as const

export const PROFESSION_ENUM = {
	HOST: "HOST",
	CHEF: "CHEF",
	BARTENDER: "BARTENDER",
	TECHNICIAN: "TECHNICIAN",
	GUARDIAN: "GUARDIAN",
	ARTIST: "ARTIST",
	STORYTELLER: "STORYTELLER",
	PSYCHOLOGIST: "PSYCHOLOGIST",
	NONE: "NONE",
} as const
export const PROFESSION_ENUM_VALUES = [
	PROFESSION_ENUM.HOST,
	PROFESSION_ENUM.CHEF,
	PROFESSION_ENUM.BARTENDER,
	PROFESSION_ENUM.TECHNICIAN,
	PROFESSION_ENUM.GUARDIAN,
	PROFESSION_ENUM.ARTIST,
	PROFESSION_ENUM.STORYTELLER,
	PROFESSION_ENUM.PSYCHOLOGIST,
	PROFESSION_ENUM.NONE,
] as const

export const COMMUNICATION_STYLE_ENUM = {
	FRIENDLY: "FRIENDLY",
	FORMAL: "FORMAL",
	CASUAL: "CASUAL",
	SARCASTIC: "SARCASTIC",
	RESERVED: "RESERVED",
	ENTHUSIASTIC: "ENTHUSIASTIC",
	NEUTRAL: "NEUTRAL",
} as const
export const COMMUNICATION_STYLE_ENUM_VALUES = [
	COMMUNICATION_STYLE_ENUM.FRIENDLY,
	COMMUNICATION_STYLE_ENUM.FORMAL,
	COMMUNICATION_STYLE_ENUM.CASUAL,
	COMMUNICATION_STYLE_ENUM.SARCASTIC,
	COMMUNICATION_STYLE_ENUM.RESERVED,
	COMMUNICATION_STYLE_ENUM.ENTHUSIASTIC,
	COMMUNICATION_STYLE_ENUM.NEUTRAL,
] as const

export const PERCEIVED_AGE_ENUM = {
	CHILD: "CHILD",
	TEEN: "TEEN",
	YOUNG_ADULT: "YOUNG_ADULT",
	ADULT: "ADULT",
	SENIOR: "SENIOR",
} as const
export const PERCEIVED_AGE_ENUM_VALUES = [
	PERCEIVED_AGE_ENUM.CHILD,
	PERCEIVED_AGE_ENUM.TEEN,
	PERCEIVED_AGE_ENUM.YOUNG_ADULT,
	PERCEIVED_AGE_ENUM.ADULT,
	PERCEIVED_AGE_ENUM.SENIOR,
] as const

export const KNOWLEDGE_DEPTH_ENUM = {
	BASIC: "BASIC",
	INTERMEDIATE: "INTERMEDIATE",
	ADVANCED: "ADVANCED",
	EXPERT: "EXPERT",
} as const
export const KNOWLEDGE_DEPTH_ENUM_VALUES = [
	KNOWLEDGE_DEPTH_ENUM.BASIC,
	KNOWLEDGE_DEPTH_ENUM.INTERMEDIATE,
	KNOWLEDGE_DEPTH_ENUM.ADVANCED,
	KNOWLEDGE_DEPTH_ENUM.EXPERT,
] as const

export const RELATIONSHIP_TYPE_ENUM = {
	COMPANION: "COMPANION",
	GUIDE: "GUIDE",
	TEACHER: "TEACHER",
	HELPER: "HELPER",
	GUARDIAN: "GUARDIAN",
	ENTERTAINER: "ENTERTAINER",
} as const
export const RELATIONSHIP_TYPE_ENUM_VALUES = [
	RELATIONSHIP_TYPE_ENUM.COMPANION,
	RELATIONSHIP_TYPE_ENUM.GUIDE,
	RELATIONSHIP_TYPE_ENUM.TEACHER,
	RELATIONSHIP_TYPE_ENUM.HELPER,
	RELATIONSHIP_TYPE_ENUM.GUARDIAN,
	RELATIONSHIP_TYPE_ENUM.ENTERTAINER,
] as const

export const ROLE_MODE_ENUM = {
	ACTIVE: "ACTIVE",
	PASSIVE: "PASSIVE",
	OBSERVER: "OBSERVER",
	ADVISOR: "ADVISOR",
} as const

export const FACT_KIND_ENUM = {
	USER_FACT: "user_fact",
	PREFERENCE: "preference",
	OBSERVATION: "observation",
} as const
export const FACT_KIND_ENUM_VALUES = [
	FACT_KIND_ENUM.USER_FACT,
	FACT_KIND_ENUM.PREFERENCE,
	FACT_KIND_ENUM.OBSERVATION,
] as const
export const DEFAULT_FACT_KIND = FACT_KIND_ENUM.OBSERVATION

export const EMOTION_EXPRESSION_STYLE_ENUM = {
	MINIMAL: "minimal",
	BALANCED: "balanced",
	TALKATIVE: "talkative",
} as const
export const EMOTION_EXPRESSION_STYLE_ENUM_VALUES = [
	EMOTION_EXPRESSION_STYLE_ENUM.MINIMAL,
	EMOTION_EXPRESSION_STYLE_ENUM.BALANCED,
	EMOTION_EXPRESSION_STYLE_ENUM.TALKATIVE,
] as const
export const DEFAULT_EMOTION_EXPRESSION_STYLE =
	EMOTION_EXPRESSION_STYLE_ENUM.BALANCED
export const ROLE_MODE_ENUM_VALUES = [
	ROLE_MODE_ENUM.ACTIVE,
	ROLE_MODE_ENUM.PASSIVE,
	ROLE_MODE_ENUM.OBSERVER,
	ROLE_MODE_ENUM.ADVISOR,
] as const

export const WAKE_WORD_ENGINE_ENUM = {
	KWS: "KWS",
} as const
export const WAKE_WORD_ENGINE_ENUM_VALUES = [WAKE_WORD_ENGINE_ENUM.KWS] as const

export const STT_ENGINE_ENUM = {
	WHISPER: "WHISPER",
	MOONSHINE: "MOONSHINE",
	ZIPFORMER: "ZIPFORMER",
	PARAKEET: "PARAKEET",
	PARAKEET_STREAMING: "PARAKEET_STREAMING",
} as const
export const STT_ENGINE_ENUM_VALUES = [
	STT_ENGINE_ENUM.WHISPER,
	STT_ENGINE_ENUM.MOONSHINE,
	STT_ENGINE_ENUM.ZIPFORMER,
	STT_ENGINE_ENUM.PARAKEET,
	STT_ENGINE_ENUM.PARAKEET_STREAMING,
] as const

export const LLM_ENGINE_ENUM = {
	OLLAMA: "OLLAMA",
	OPENAI_COMPATIBLE: "OPENAI_COMPATIBLE",
} as const
export const LLM_ENGINE_ENUM_VALUES = [
	LLM_ENGINE_ENUM.OLLAMA,
	LLM_ENGINE_ENUM.OPENAI_COMPATIBLE,
] as const

export const TTS_ENGINE_ENUM = {
	KOKORO: "KOKORO",
	POCKET: "POCKET",
	VITS: "VITS",
} as const
export const TTS_ENGINE_ENUM_VALUES = [
	TTS_ENGINE_ENUM.KOKORO,
	TTS_ENGINE_ENUM.POCKET,
	TTS_ENGINE_ENUM.VITS,
] as const

export const WAKE_WORD_FRAMEWORK_ENUM = {
	ONNX: "onnx",
} as const
export const WAKE_WORD_FRAMEWORK_ENUM_VALUES = [
	WAKE_WORD_FRAMEWORK_ENUM.ONNX,
] as const

export const AUDIO_PLAYBACK_ENGINE_ENUM = {
	SOX: "SOX",
	PLAY_SOUND: "PLAY-SOUND",
} as const
export const AUDIO_PLAYBACK_ENGINE_ENUM_VALUES = [
	AUDIO_PLAYBACK_ENGINE_ENUM.SOX,
	AUDIO_PLAYBACK_ENGINE_ENUM.PLAY_SOUND,
] as const

export const INTERACTION_INPUT_TYPE_ENUM = {
	VOICE: "VOICE",
	TEXT: "TEXT",
} as const
export const INTERACTION_INPUT_TYPE_ENUM_VALUES = [
	INTERACTION_INPUT_TYPE_ENUM.VOICE,
	INTERACTION_INPUT_TYPE_ENUM.TEXT,
] as const

export const RESPONSE_TYPE_ENUM = {
	TEXT: "text",
	VOICE: "voice",
} as const
export const RESPONSE_TYPE_ENUM_VALUES = [
	RESPONSE_TYPE_ENUM.TEXT,
	RESPONSE_TYPE_ENUM.VOICE,
] as const

export const INTERACTION_STATUS_ENUM = {
	OK: "ok",
	FAILED: "failed",
	ABORTED: "aborted",
	NO_SPEECH: "no_speech",
} as const
export const INTERACTION_STATUS_ENUM_VALUES = [
	INTERACTION_STATUS_ENUM.OK,
	INTERACTION_STATUS_ENUM.FAILED,
	INTERACTION_STATUS_ENUM.ABORTED,
	INTERACTION_STATUS_ENUM.NO_SPEECH,
] as const

export const MQTT_TYPE_ENUM = {
	LOCAL: "LOCAL",
} as const
export const MQTT_TYPE_ENUM_VALUES = [MQTT_TYPE_ENUM.LOCAL] as const

export const MQTT_PROTOCOL_ENUM = {
	MQTT: "mqtt",
	MQTTS: "mqtts",
	WS: "ws",
	WSS: "wss",
} as const
export const MQTT_PROTOCOL_ENUM_VALUES = [
	MQTT_PROTOCOL_ENUM.MQTT,
	MQTT_PROTOCOL_ENUM.MQTTS,
	MQTT_PROTOCOL_ENUM.WS,
	MQTT_PROTOCOL_ENUM.WSS,
] as const

export const CAPABILITY_ENUM = {
	RECORD: "record",
	STT: "stt",
	LLM: "llm",
	TTS: "tts",
	PLAYBACK: "playback",
} as const
export const CAPABILITY_ENUM_VALUES = [
	CAPABILITY_ENUM.RECORD,
	CAPABILITY_ENUM.STT,
	CAPABILITY_ENUM.LLM,
	CAPABILITY_ENUM.TTS,
	CAPABILITY_ENUM.PLAYBACK,
] as const

export const SATELLITE_PROTOCOL_ENUM = {
	NATIVE: "native",
	WYOMING: "wyoming",
	ESPHOME: "esphome",
	LIVEKIT: "livekit",
	OPENAI_REALTIME: "openai-realtime",
} as const
export const SATELLITE_PROTOCOL_ENUM_VALUES = [
	SATELLITE_PROTOCOL_ENUM.NATIVE,
	SATELLITE_PROTOCOL_ENUM.WYOMING,
	SATELLITE_PROTOCOL_ENUM.ESPHOME,
	SATELLITE_PROTOCOL_ENUM.LIVEKIT,
	SATELLITE_PROTOCOL_ENUM.OPENAI_REALTIME,
] as const
export const IMPLICIT_FEEDBACK_ENUM = {
	BARGE_IN: "barge_in",
	REPHRASE: "rephrase",
	SATISFIED: "satisfied",
} as const
export const IMPLICIT_FEEDBACK_ENUM_VALUES = [
	IMPLICIT_FEEDBACK_ENUM.BARGE_IN,
	IMPLICIT_FEEDBACK_ENUM.REPHRASE,
	IMPLICIT_FEEDBACK_ENUM.SATISFIED,
] as const

export const DEFAULT_SATELLITE_PROTOCOL = SATELLITE_PROTOCOL_ENUM.ESPHOME
export const DEFAULT_SATELLITE_PORT = 6053
export const DEFAULT_WYOMING_PORT = 10700
export const DEFAULT_LIVEKIT_PORT = 7880
export const DEFAULT_SATELLITE_PORT_BY_PROTOCOL: Record<string, number> = {
	[SATELLITE_PROTOCOL_ENUM.ESPHOME]: DEFAULT_SATELLITE_PORT,
	[SATELLITE_PROTOCOL_ENUM.NATIVE]: DEFAULT_SATELLITE_PORT,
	[SATELLITE_PROTOCOL_ENUM.WYOMING]: DEFAULT_WYOMING_PORT,
	[SATELLITE_PROTOCOL_ENUM.LIVEKIT]: DEFAULT_LIVEKIT_PORT,
}
export const DEFAULT_SATELLITE_ACTIVE = true
export const DEFAULT_ESPHOME_DISCOVERY_MS = 4000
export const DEFAULT_SATELLITE_RECONNECT_MS = 5000
export const DEFAULT_SATELLITE_RECONNECT_MAX_MS = 60_000
export const DEFAULT_SATELLITE_RECONNECT_JITTER = 0.3
export const DEFAULT_SATELLITE_TURN_TIMEOUT_MS = 30_000
export const DEFAULT_DESIRED_WAKE_WORDS: string[] = []
export const DEFAULT_SATELLITE_DESIRED_NUMBERS: Record<string, number> = {}
export const DEFAULT_SATELLITE_FOLLOW_UP = false

export const SKILL_PROTOCOL_ENUM = {
	MCP: "mcp",
	HTTP: "http",
	MQTT: "mqtt",
} as const
export const SKILL_PROTOCOL_ENUM_VALUES = [
	SKILL_PROTOCOL_ENUM.MCP,
	SKILL_PROTOCOL_ENUM.HTTP,
	SKILL_PROTOCOL_ENUM.MQTT,
] as const

export const ANNOUNCEMENT_KIND_ENUM = {
	TEXT: "text",
	AUDIO: "audio",
} as const
export const ANNOUNCEMENT_KIND_ENUM_VALUES = [
	ANNOUNCEMENT_KIND_ENUM.TEXT,
	ANNOUNCEMENT_KIND_ENUM.AUDIO,
] as const

export const ANNOUNCEMENT_DELIVERY_ENUM = {
	ORIGINAL: "original",
	DOMIA_VOICE: "domia-voice",
} as const
export const ANNOUNCEMENT_DELIVERY_ENUM_VALUES = [
	ANNOUNCEMENT_DELIVERY_ENUM.ORIGINAL,
	ANNOUNCEMENT_DELIVERY_ENUM.DOMIA_VOICE,
] as const

export const MCP_TRANSPORT_ENUM = {
	HTTP: "http",
	SSE: "sse",
} as const
export const MCP_TRANSPORT_ENUM_VALUES = [
	MCP_TRANSPORT_ENUM.HTTP,
	MCP_TRANSPORT_ENUM.SSE,
] as const

export const AGENT_PROMPT_MODE_ENUM = {
	LEAN: "lean",
	COMPACT: "compact",
	FULL: "full",
} as const
export const AGENT_PROMPT_MODE_ENUM_VALUES = [
	AGENT_PROMPT_MODE_ENUM.LEAN,
	AGENT_PROMPT_MODE_ENUM.COMPACT,
	AGENT_PROMPT_MODE_ENUM.FULL,
] as const
export const DEFAULT_AGENT_PROMPT_MODE = AGENT_PROMPT_MODE_ENUM.COMPACT

export const SKILLS_ROUTING_ENUM = {
	ALWAYS_AGENT: "always-agent",
	INTENT_GATE: "intent-gate",
	EMBEDDING_GATE: "embedding-gate",
	FAST_ROUTER: "fast-router",
} as const
export const SKILLS_ROUTING_ENUM_VALUES = [
	SKILLS_ROUTING_ENUM.ALWAYS_AGENT,
	SKILLS_ROUTING_ENUM.INTENT_GATE,
	SKILLS_ROUTING_ENUM.EMBEDDING_GATE,
	SKILLS_ROUTING_ENUM.FAST_ROUTER,
] as const
export const DEFAULT_SKILLS_ROUTING = SKILLS_ROUTING_ENUM.EMBEDDING_GATE
export const DEFAULT_INTENT_MODEL = "llama3.2:3b"
export const DEFAULT_EMBEDDING_MODEL = "nomic-embed-text"
export const DEFAULT_INTENT_EMBED_THRESHOLD = 0.66
export const DEFAULT_DESCRIPTOR_ROUTING_ENABLED = false
export const DEFAULT_EMBED_MODEL_PATH = "data/models/bge-small-en-v1.5"
export const MATCHER_ENGINE_ENUM = {
	LEXICAL: "lexical",
	SEMANTIC: "semantic",
	HYBRID: "hybrid",
} as const
export const MATCHER_ENGINE_ENUM_VALUES = [
	MATCHER_ENGINE_ENUM.LEXICAL,
	MATCHER_ENGINE_ENUM.SEMANTIC,
	MATCHER_ENGINE_ENUM.HYBRID,
] as const
export const DEFAULT_MATCHER_ENGINE = MATCHER_ENGINE_ENUM.HYBRID
export const DEFAULT_MATCHER_SEMANTIC_THRESHOLD = 0.55
export const DEFAULT_MATCHER_RRF_K = 60
export const DEFAULT_MATCHER_CASCADE_EXIT = 6
export const EMBED_BACKEND_ENUM = {
	TRANSFORMERS: "transformers",
	OLLAMA: "ollama",
} as const
export const EMBED_BACKEND_ENUM_VALUES = [
	EMBED_BACKEND_ENUM.TRANSFORMERS,
	EMBED_BACKEND_ENUM.OLLAMA,
] as const
export const DEFAULT_EMBED_BACKEND = EMBED_BACKEND_ENUM.TRANSFORMERS

export const DEFAULT_METRICS_SAMPLE_RESOURCES = true
export const DEFAULT_TURN_EVENTS_PERSIST = true
export const DEFAULT_TURN_EVENT_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000
export const DEFAULT_TURN_EVENT_MAX_ROWS_PER_DOMIA = 5000

export const DEFAULT_SKILLS_ENGINE = false
export const DEFAULT_SKILL_PROTOCOL = SKILL_PROTOCOL_ENUM.MCP
export const DEFAULT_MCP_TRANSPORT_TYPE = MCP_TRANSPORT_ENUM.HTTP
export const HA_DATA_PLANE_ENUM = {
	WS: "ws",
	POLL: "poll",
} as const
export const HA_DATA_PLANE_ENUM_VALUES = [
	HA_DATA_PLANE_ENUM.WS,
	HA_DATA_PLANE_ENUM.POLL,
] as const
export const DEFAULT_HA_DATA_PLANE = HA_DATA_PLANE_ENUM.POLL
export const DEFAULT_HA_WS_PATH = "/api/websocket"
export const DEFAULT_HA_WS_HANDSHAKE_TIMEOUT_MS = 10_000
export const DEFAULT_HA_WS_AUTH_TIMEOUT_MS = 10_000
export const DEFAULT_HA_WS_COMMAND_TIMEOUT_MS = 10_000
export const DEFAULT_HA_WS_HEARTBEAT_INTERVAL_MS = 30_000
export const DEFAULT_HA_WS_HEARTBEAT_TIMEOUT_MS = 10_000
export const DEFAULT_HA_WS_RECONNECT_MS = 1_000
export const DEFAULT_HA_WS_RECONNECT_MAX_MS = 60_000
export const DEFAULT_HA_WS_RECONNECT_JITTER = 0.3
export const DEFAULT_HA_WS_MAX_ENTITIES = 5_000
export const DEFAULT_SKILL_MAX_RESULT_CHARS = 4000
export const DEFAULT_SKILL_REFRESH_MS = 300_000
export const DEFAULT_SKILL_TIMEOUT_MS = 8000
export const DEFAULT_AGENT_MAX_STEPS = 5
export const DEFAULT_SLOW_TOOL_AFTER_MS = 1200
export const DEFAULT_AGENT_ACK_AFTER_MS = 600
export const DEFAULT_TOOL_SHORTLIST_MAX = 8
export const DEFAULT_SKILL_RETRY_MAX_ATTEMPTS = 1
export const DEFAULT_SKILL_RETRY_BACKOFF_MS = 200
export const DEFAULT_SKILL_BREAKER_THRESHOLD = 0
export const DEFAULT_SKILL_BREAKER_COOLDOWN_MS = 30_000
export const DEFAULT_AGENT_BUDGET_MS = 0
export const DEFAULT_CONFIRMATION_TTL_MS = 120_000
export const DEFAULT_SKILL_IDEMPOTENT_WITHIN_TURN = false
export const SKILL_TOOL_NAME_SEPARATOR = "__"
export const DEFAULT_FINALIZE_ACK = "Done."
export const DEFAULT_FINALIZE_ERROR = "Sorry, I couldn't do that."
export const DEFAULT_TMP_AUDIO_TTL_MS = 86_400_000
export const DEFAULT_TMP_SWEEP_INTERVAL_MS = 3_600_000

export const DEFAULT_RETENTION_SWEEP_INTERVAL_MS = 3_600_000
export const DEFAULT_TRACE_MAX_AGE_MS = 90 * 86_400_000
export const DEFAULT_TRACE_MAX_ROWS_PER_DOMIA = 5_000
export const DEFAULT_TRACE_MAX_ROWS_GLOBAL = 50_000
export const DEFAULT_EMOTION_EVENT_MAX_AGE_MS = 90 * 86_400_000
export const DEFAULT_EMOTION_EVENT_MAX_ROWS_PER_DOMIA = 5_000
export const DEFAULT_ANNOUNCEMENT_MAX_AGE_MS = 7 * 86_400_000
export const DEFAULT_MEMORY_FACT_MAX_ROWS_PER_DOMIA = 2_000
export const DEFAULT_MEMORY_EPISODE_MAX_AGE_MS = 180 * 86_400_000
export const DEFAULT_MEMORY_EPISODE_MAX_ROWS_PER_DOMIA = 1_000
export const DEFAULT_MQTT_HOST = "localhost"
export const DEFAULT_MQTT_USERNAME = "domia"
export const DEFAULT_MQTT_PASSWORD = "domia"
export const DEFAULT_MQTT_TOPIC_ROOT = "domia"
