export const DEFAULT_LANGUAGE = "en"
export const DEFAULT_WAKE_WORD = "domia"
export const DEFAULT_WAKE_WORD_MODEL = "domia"
export const DEFAULT_LLM_MODEL_TEMPERATURE = 0.7
export const DEFAULT_LLM_MODEL_CONTEXT_WINDOW = 2048
export const DEFAULT_STT_MODEL_NAME = "vosk-model-small-en-us-0.15"
export const DEFAULT_LLM_MODEL_NAME = "tinyllama"
export const DEFAULT_TTS_VOICE_NAME = "en_US-libritts_r-medium"

export const PERSONALITY_ENUM = {
	OPTIMISTIC: "OPTIMISTIC",
	CALM: "CALM",
	ANALYTICAL: "ANALYTICAL",
	EMPATHETIC: "EMPATHETIC",
	NEUTRAL: "NEUTRAL",
	PLAYFUL: "PLAYFUL",
	CAUTIOUS: "CAUTIOUS",
	ADAPTIVE: "ADAPTIVE",
	CUSTOM: "CUSTOM",
} as const
export const PERSONALITY_ENUM_VALUES = [
	PERSONALITY_ENUM.OPTIMISTIC,
	PERSONALITY_ENUM.CALM,
	PERSONALITY_ENUM.ANALYTICAL,
	PERSONALITY_ENUM.EMPATHETIC,
	PERSONALITY_ENUM.NEUTRAL,
	PERSONALITY_ENUM.PLAYFUL,
	PERSONALITY_ENUM.CAUTIOUS,
	PERSONALITY_ENUM.ADAPTIVE,
	PERSONALITY_ENUM.CUSTOM,
] as const

export const PROFESSION_ENUM = {
	HOST: "HOST",
	CHEF: "CHEF",
	BARTENDER: "BARTENDER",
	TECHNICIAN: "TECHNICIAN",
	GUARDIAN: "GUARDIAN",
	ARTIST: "ARTIST",
	STORYTELLER: "STORYTELLER",
	PSYCHOLOGIST: "PSYCHOLOGIST",
	NONE: "NONE",
} as const
export const PROFESSION_ENUM_VALUES = [
	PROFESSION_ENUM.HOST,
	PROFESSION_ENUM.CHEF,
	PROFESSION_ENUM.BARTENDER,
	PROFESSION_ENUM.TECHNICIAN,
	PROFESSION_ENUM.GUARDIAN,
	PROFESSION_ENUM.ARTIST,
	PROFESSION_ENUM.STORYTELLER,
	PROFESSION_ENUM.PSYCHOLOGIST,
	PROFESSION_ENUM.NONE,
] as const

export const COMMUNICATION_STYLE_ENUM = {
	FRIENDLY: "FRIENDLY",
	FORMAL: "FORMAL",
	CASUAL: "CASUAL",
	SARCASTIC: "SARCASTIC",
	RESERVED: "RESERVED",
	ENTHUSIASTIC: "ENTHUSIASTIC",
	NEUTRAL: "NEUTRAL",
} as const
export const COMMUNICATION_STYLE_ENUM_VALUES = [
	COMMUNICATION_STYLE_ENUM.FRIENDLY,
	COMMUNICATION_STYLE_ENUM.FORMAL,
	COMMUNICATION_STYLE_ENUM.CASUAL,
	COMMUNICATION_STYLE_ENUM.SARCASTIC,
	COMMUNICATION_STYLE_ENUM.RESERVED,
	COMMUNICATION_STYLE_ENUM.ENTHUSIASTIC,
	COMMUNICATION_STYLE_ENUM.NEUTRAL,
] as const

export const PERCEIVED_AGE_ENUM = {
	CHILD: "CHILD",
	TEEN: "TEEN",
	YOUNG_ADULT: "YOUNG_ADULT",
	ADULT: "ADULT",
	SENIOR: "SENIOR",
} as const
export const PERCEIVED_AGE_ENUM_VALUES = [
	PERCEIVED_AGE_ENUM.CHILD,
	PERCEIVED_AGE_ENUM.TEEN,
	PERCEIVED_AGE_ENUM.YOUNG_ADULT,
	PERCEIVED_AGE_ENUM.ADULT,
	PERCEIVED_AGE_ENUM.SENIOR,
] as const

export const KNOWLEDGE_DEPTH_ENUM = {
	BASIC: "BASIC",
	INTERMEDIATE: "INTERMEDIATE",
	ADVANCED: "ADVANCED",
	EXPERT: "EXPERT",
} as const
export const KNOWLEDGE_DEPTH_ENUM_VALUES = [
	KNOWLEDGE_DEPTH_ENUM.BASIC,
	KNOWLEDGE_DEPTH_ENUM.INTERMEDIATE,
	KNOWLEDGE_DEPTH_ENUM.ADVANCED,
	KNOWLEDGE_DEPTH_ENUM.EXPERT,
] as const

export const RELATIONSHIP_TYPE_ENUM = {
	COMPANION: "COMPANION",
	GUIDE: "GUIDE",
	TEACHER: "TEACHER",
	HELPER: "HELPER",
	GUARDIAN: "GUARDIAN",
	ENTERTAINER: "ENTERTAINER",
} as const
export const RELATIONSHIP_TYPE_ENUM_VALUES = [
	RELATIONSHIP_TYPE_ENUM.COMPANION,
	RELATIONSHIP_TYPE_ENUM.GUIDE,
	RELATIONSHIP_TYPE_ENUM.TEACHER,
	RELATIONSHIP_TYPE_ENUM.HELPER,
	RELATIONSHIP_TYPE_ENUM.GUARDIAN,
	RELATIONSHIP_TYPE_ENUM.ENTERTAINER,
] as const

export const ROLE_MODE_ENUM = {
	ACTIVE: "ACTIVE",
	PASSIVE: "PASSIVE",
	OBSERVER: "OBSERVER",
	ADVISOR: "ADVISOR",
} as const
export const ROLE_MODE_ENUM_VALUES = [
	ROLE_MODE_ENUM.ACTIVE,
	ROLE_MODE_ENUM.PASSIVE,
	ROLE_MODE_ENUM.OBSERVER,
	ROLE_MODE_ENUM.ADVISOR,
] as const

export const WAKE_WORD_ENGINE_ENUM = {
	OPEN_WAKE_WORD: "OPEN_WAKE_WORD",
	PORCUPINE: "PORCUPINE",
} as const
export const WAKE_WORD_ENGINE_ENUM_VALUES = [
	WAKE_WORD_ENGINE_ENUM.OPEN_WAKE_WORD,
	WAKE_WORD_ENGINE_ENUM.PORCUPINE,
] as const

export const STT_ENGINE_ENUM = {
	VOSK: "VOSK",
	WHISPER: "WHISPER",
} as const
export const STT_ENGINE_ENUM_VALUES = [
	STT_ENGINE_ENUM.VOSK,
	STT_ENGINE_ENUM.WHISPER,
] as const

export const LLM_ENGINE_ENUM = {
	OLLAMA: "OLLAMA",
	LLAMA_CPP: "LLAMA_CPP",
} as const
export const LLM_ENGINE_ENUM_VALUES = [
	LLM_ENGINE_ENUM.OLLAMA,
	LLM_ENGINE_ENUM.LLAMA_CPP,
] as const

export const TTS_ENGINE_ENUM = {
	PIPER: "PIPER",
	COQUI: "COQUI",
} as const
export const TTS_ENGINE_ENUM_VALUES = [
	TTS_ENGINE_ENUM.PIPER,
	TTS_ENGINE_ENUM.COQUI,
] as const

export const WAKE_WORD_FRAMEWORK_ENUM = {
	ONNX: "onnx",
	TFLITE: "tflite",
} as const
export const WAKE_WORD_FRAMEWORK_ENUM_VALUES = [
	WAKE_WORD_FRAMEWORK_ENUM.ONNX,
	WAKE_WORD_FRAMEWORK_ENUM.TFLITE,
] as const

export const AUDIO_PLAYBACK_ENGINE_ENUM = {
	SOX: "SOX",
	PLAY_SOUND: "PLAY-SOUND",
} as const
export const AUDIO_PLAYBACK_ENGINE_ENUM_VALUES = [
	AUDIO_PLAYBACK_ENGINE_ENUM.SOX,
	AUDIO_PLAYBACK_ENGINE_ENUM.PLAY_SOUND,
] as const

export const INTERACTION_INPUT_TYPE_ENUM = {
	VOICE: "VOICE",
	TEXT: "TEXT",
} as const
export const INTERACTION_INPUT_TYPE_ENUM_VALUES = [
	INTERACTION_INPUT_TYPE_ENUM.VOICE,
	INTERACTION_INPUT_TYPE_ENUM.TEXT,
] as const
