persistence true
persistence_location /mosquitto/data/
persistence_file domia-mqtt.db

log_dest file /mosquitto/log/mosquitto.log

allow_anonymous false
password_file /mosquitto/config/password.txt

listener 1883
listener 9001
protocol websockets
